kind: Deployment
apiVersion: apps/v1
metadata:
  name:  {{ .Release.Name }}-maintenance
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-maintenance
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-maintenance
    spec:
      restartPolicy: Always
      containers:
      - name: {{ .Release.Name }}-maintenance
        image: "{{ .Values.maintenance.image.repository }}:{{ .Values.maintenance.image.tag | default (include "defaultTag" .)  }}"
        imagePullPolicy: {{ quote .Values.global.image.pullPolicy }}
        {{- include "resources" .Values.maintenance.resources | indent 8 }}
        env:
          - name: HOST
            value: 0.0.0.0
        ports:
          - containerPort: 80
