enum EmailNotificationSettingsName {
  commentOnObservedPost
  mention
  followingUsers
  postInGroup
  chatMessage
  groupMemberJoined
  groupMemberLeft
  groupMemberRemoved
  groupMemberRoleChanged
}
