backend: &backend
  - '.github/workflows/test-backend.yml'
  - 'backend/**/*'
  - 'neo4j/**/*'
  - 'package.json'

docker: &docker
  - 'docker-compose.*'

webapp: &webapp
  - '.github/workflows/test-webapp.yml'
  - 'webapp/**/*'
  - 'package.json'

docs-check: &docs-check
  - '.github/workflows/check-documentation.yml'

markdown: &markdown
  - *docs-check
  - '**/*.md'
  - '.github/workflows/mlc_config.json'

vuepress: &vuepress
  - *docs-check
  - '.github/workflows/deploy-documentation.yml'
  - '.vuepress/**/*'
  - 'package.json'

documentation: &documentation
  - *vuepress
  - *markdown
