backend: &backend
  - '.github/workflows/test-backend.yml'
  - 'backend/**/*'
  - 'neo4j/**/*'

docker: &docker
  - 'docker-compose.*'

webapp: &webapp
  - '.github/workflows/test-webapp.yml'
  - 'webapp/**/*'
