# These file filter patterns are used by the action https://github.com/dorny/paths-filter

frontend-test-lint-code: &frontend-test-lint-code
  - '**/*'

frontend-test-unit-code: &frontend-test-unit-code
  - '**/*'

frontend-test-build-code: &frontend-test-build-code
  - '**/*'

frontend-test-build-docs: &frontend-test-build-docs
  - '**/*.md'
  - '.vuepress/'

frontend-test-build-storybook: &frontend-test-build-storybook
  - '**/*'