services:

  webapp:
    image: ${IMAGE_REPOSITORY:-ghcr.io/ocelot-social-community/stage.ocelot.social}/webapp:ocelot-${OCELOT_VERSION:-master}--branded-${BRANDED_VERSION:-master}
    build:
      target: branded
      context: ${CONTEXT:-./deployment/configurations/stage.ocelot.social}
      dockerfile: ./docker/backend.Dockerfile
      args:
        OCELOT_VERSION: ${OCELOT_VERSION:-master}

  backend:
    image: ${IMAGE_REPOSITORY:-ghcr.io/ocelot-social-community/stage.ocelot.social}/backend:ocelot-${OCELOT_VERSION:-master}--branded-${BRANDED_VERSION:-master}
    build:
      target: branded
      context: ${CONTEXT:-./deployment/configurations/stage.ocelot.social}
      dockerfile: ./docker/webapp.Dockerfile
      args:
        OCELOT_VERSION: ${OCELOT_VERSION:-master}

  maintenance:
    image: ${IMAGE_REPOSITORY:-ghcr.io/ocelot-social-community/stage.ocelot.social}/maintenance:ocelot-${OCELOT_VERSION:-master}--branded-${BRANDED_VERSION:-master}
    build:
      target: branded
      context: ${CONTEXT:-./deployment/configurations/stage.ocelot.social}
      dockerfile: ./docker/maintenance.Dockerfile
      args:
        OCELOT_VERSION: ${OCELOT_VERSION:-master}
