services:

  webapp:
    image: ghcr.io/ocelot-social-community/ocelot-social/webapp-build:${OCELOT_VERSION:-latest}
    build:
      target: build
      context: webapp

  backend:
    image: ghcr.io/ocelot-social-community/ocelot-social/backend-build:${OCELOT_VERSION:-latest}
    build:
      target: build
      context: backend

  maintenance:
    image: ghcr.io/ocelot-social-community/ocelot-social/maintenance-build:${OCELOT_VERSION:-latest}
    build:
      target: build
      context: webapp
      dockerfile: ./Dockerfile.maintenance
