language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - node_module

install:
  - yarn install --production=false --frozen-lockfile --non-interactive
  - yarn build
  - yarn build:lib

before_deploy:
  - rm -Rf ./node_modules .docs ./preview ./tests *.log*
  - rm -Rf ./src/system/icons/_all
  - rm -Rf ./src/system/tokens/_examples

deploy:
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    on:
      condition: ./deployment_condition.sh
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    on:
      condition: ./deployment_condition.sh
