query currentUser {
  currentUser {
    id
    slug
    name
    avatar {
      url
    }
    email
    roleName
    activeCategories
    following(nameFilter: "") {
      id
      name
    }
    inviteCodes {
      code
      redeemedByCount
    }
  }
}
