import cypherFields from './helpers/cypherField'
import { nodeQuery } from './helpers/nodeQuery'
import Resolver from './helpers/Resolver'

import type { NodeQueryParams } from './helpers/nodeQuery'
import type { Context } from '@src/context'

const categoryQuery = nodeQuery({
  label: 'Category',
  equalityFields: ['id', 'name', 'slug', 'icon', 'createdAt', 'updatedAt'],
  orderable: ['id', 'name', 'slug', 'icon', 'createdAt', 'updatedAt'],
  defaultOrder: 'category.name ASC',
})

// Category has no root resolver of its own — the Category query is generated by
// neo4j-graphql-js. This file exists for the FIELD resolvers, so Category.posts resolves
// even when the parent did not come out of a neo4jgraphql() translation (a hand-written
// resolver, a subscription payload). See the migration plan, stage B2.
//
// Deliberately unfiltered, matching the @relation directive it replaces: this returns every
// post of the category. Visibility filtering happens in the queries that surface posts, and
// changing that here would be a behaviour change smuggled into a mechanical migration.
export default {
  Query: {
    // Stage D: the last generated root queries. Category advertises no filter beyond the
    // scalar arguments, so equality + ordering + paging is the whole contract.
    Category: async (_object, params: NodeQueryParams, context: Context, _resolveInfo) =>
      categoryQuery(params, context),
  },
  Category: {
    ...Resolver('Category', {
      hasMany: {
        posts: '<-[:CATEGORIZED]-(related:Post)',
      },
    }),
    ...cypherFields('Category', {
      postCount: 'MATCH (this)<-[:CATEGORIZED]-(r:Post) RETURN COUNT(r)',
    }),
  },
}
