import Resolver from './helpers/Resolver'

// Category has no root resolver of its own — the Category query is generated by
// neo4j-graphql-js. This file exists for the FIELD resolvers, so Category.posts resolves
// even when the parent did not come out of a neo4jgraphql() translation (a hand-written
// resolver, a subscription payload). See the migration plan, stage B2.
//
// Deliberately unfiltered, matching the @relation directive it replaces: this returns every
// post of the category. Visibility filtering happens in the queries that surface posts, and
// changing that here would be a behaviour change smuggled into a mechanical migration.
export default {
  Category: {
    ...Resolver('Category', {
      hasMany: {
        posts: '<-[:CATEGORIZED]-(related:Post)',
      },
    }),
  },
}
