type Badge {
  id: ID!
  type: BadgeType!
  icon: String!
  createdAt: String

  rewarded: [User]! @relation(name: "REWARDED", direction: "OUT")
  verifies: [User]! @relation(name: "VERIFIES", direction: "OUT")
}

enum BadgeType {
  verification
  badge
}

type Query {
  Badge: [Badge]
}

type Mutation {
  setVerificationBadge(badgeId: ID!, userId: ID!): User
  rewardBadge(badgeId: ID!, userId: ID!): User
  revokeBadge(badgeId: ID!, userId: ID!): User
}
