type Badge {
  id: ID!
  type: BadgeType!
  icon: String!
  createdAt: String

  rewarded: [User]! @relation(name: "REWARDED", direction: "OUT")
  verified: [User]! @relation(name: "VERIFIED", direction: "OUT")
}

enum BadgeType {
  verification
  badge
}

type Query {
  Badge: [Badge]
}

type Mutation {
  verify(badgeId: ID!, userId: ID!): User
  reward(badgeId: ID!, userId: ID!): User
  unreward(badgeId: ID!, userId: ID!): User
}
