type Badge {
  id: ID!
  type: BadgeType!
  status: BadgeStatus!
  icon: String!
  createdAt: String
  updatedAt: String

  rewarded: [User]! @relation(name: "REWARDED", direction: "OUT")
}

enum BadgeStatus {
  permanent
  temporary
}

enum BadgeType {
  verification
  badge
}

type Query {
  Badge: [Badge]
}

type Mutation {
  rewardBadge(badgeId: ID!, userId: ID!): User
  unrewardBadge(badgeId: ID!, userId: ID!): User
}
