type Donations {
  id: ID!
  showDonations: Boolean! # Wolle make it required in the schema
  goal: Int! # Wolle make it required in the schema
  progress: Int! # Wolle make it required in the schema
  createdAt: String
  updatedAt: String
}

type Query {
  Donations: [Donations]
}

type Mutation {
  UpdateDonations(showDonations: Boolean, goal: Int, progress: Int): Donations
}