query GroupMembers($id: ID!, $first: Int, $offset: Int, $includePending: Boolean, $nameFilter: String) {
  GroupMembers(id: $id, first: $first, offset: $offset, includePending: $includePending, nameFilter: $nameFilter) {
    user {
      id
      name
      slug
    }
    membership {
      role
    }
  }
}
