query GroupMembers($id: ID!, $includePending: Boolean) {
  GroupMembers(id: $id, includePending: $includePending) {
    user {
      id
      name
      slug
    }
    membership {
      role
    }
  }
}
