mutation RemoveUserFromGroup($groupId: ID!, $userId: ID!) {
  RemoveUserFromGroup(groupId: $groupId, userId: $userId) {
    user {
      id
      name
      slug
    }
    membership {
      role
    }
  }
}
