mutation UpdateGroup(
  $id: ID!
  $name: String
  $slug: String
  $about: String
  $description: String
  $groupType: GroupType
  $actionRadius: GroupActionRadius
  $categoryIds: [ID]
  $avatar: ImageInput
  $locationName: String # empty string '' sets it to null
  $showMembers: Boolean
) {
  UpdateGroup(
    id: $id
    name: $name
    slug: $slug
    about: $about
    description: $description
    groupType: $groupType
    actionRadius: $actionRadius
    categoryIds: $categoryIds
    avatar: $avatar
    locationName: $locationName
    showMembers: $showMembers
  ) {
    id
    name
    slug
    createdAt
    updatedAt
    disabled
    deleted
    about
    description
    groupType
    actionRadius
    categories {
      id
      slug
      name
      icon
    }
    # avatar # test this as result
    locationName
    location {
      id
      name
    }
    myRole
  }
}
