mutation markAsUnread($id: ID!) {
  markAsUnread(id: $id) {
    id
    from {
      __typename
      ... on Post {
        id
        content
      }
      ... on Comment {
        id
        content
      }
    }
    read
    createdAt
  }
}
