query notificationsPaginated(
  $read: Boolean
  $orderBy: NotificationOrdering
  $first: Int
  $offset: Int
) {
  notifications(read: $read, orderBy: $orderBy, first: $first, offset: $offset) {
    id
    read
    createdAt
  }
}
