mutation pinPost($id: ID!) {
  pinPost(id: $id) {
    id
    title
    content
    author {
      id
      name
      slug
    }
    pinnedBy {
      id
      name
      role
    }
    createdAt
    updatedAt
    pinnedAt
    pinned
  }
}
