mutation setTrophyBadgeSelected($slot: Int!, $badgeId: ID) {
  setTrophyBadgeSelected(slot: $slot, badgeId: $badgeId) {
    id
    badgeTrophiesCount
    badgeTrophiesSelected {
      id
      isDefault
    }
    badgeTrophiesUnused {
      id
    }
    badgeTrophiesUnusedCount
  }
}
