underMaintenance: false

global:
  image:
    tag:

neo4j:
  image:
    repository: ghcr.io/ocelot-social-community/ocelot-social/neo4j
    tag:

  storage: "5Gi"
  storageBackups: "10Gi"
  env:
    NEO4J_ACCEPT_LICENSE_AGREEMENT: "no"
    NEO4J_AUTH: "none"
    NEO4J_dbms_connector_bolt_thread__pool__max__size: "400"
    NEO4J_dbms_memory_heap_initial__size: ""
    NEO4J_dbms_memory_heap_max__size: ""
    NEO4J_dbms_memory_pagecache_size: ""
    NEO4J_dbms_security_procedures_unrestricted: "algo.*,apoc.*"
    NEO4J_dbms_default__database: neo4j
    NEO4J_apoc_import_file_enabled: "false"
    NEO4J_dbms_allow__format__migration: "true"
    NEO4J_dbms_allow__upgrade: "true"
