export const berlinGermany = {
  type: 'FeatureCollection',
  query: ['berlin', 'germany'],
  features: [
    {
      id: 'place.115770',
      type: 'Feature',
      place_type: ['region', 'place'],
      relevance: 1,
      properties: {
        mapbox_id: 'dXJuOm1ieHBsYzpBY1E2',
        wikidata: 'Q64',
        short_code: 'DE-BE',
      },
      text_en: 'Berlin',
      language_en: 'en',
      place_name_en: 'Berlin, Germany',
      text: 'Berlin',
      language: 'en',
      place_name: 'Berlin, Germany',
      text_de: 'Berlin',
      language_de: 'de',
      place_name_de: 'Berlin, Deutschland',
      text_fr: 'Berlin',
      language_fr: 'fr',
      place_name_fr: 'Berlin, Allemagne',
      text_nl: 'Berlijn',
      language_nl: 'nl',
      place_name_nl: 'Berlijn, Duitsland',
      text_it: 'Berlino',
      language_it: 'it',
      place_name_it: 'Berlino, Germania',
      text_es: 'Berlín',
      language_es: 'es',
      place_name_es: 'Berlín, Alemania',
      text_pt: 'Berlim',
      language_pt: 'pt',
      place_name_pt: 'Berlim, Alemanha',
      text_pl: 'Berlin',
      language_pl: 'pl',
      place_name_pl: 'Berlin, Niemcy',
      text_ru: 'Берлин',
      language_ru: 'ru',
      place_name_ru: 'Берлин, Германия',
      bbox: [13.08836, 52.338261, 13.760906, 52.675502],
      center: [13.38886, 52.517037],
      geometry: {
        type: 'Point',
        coordinates: [13.38886, 52.517037],
      },
      context: [
        {
          id: 'country.8762',
          mapbox_id: 'dXJuOm1ieHBsYzpJam8',
          wikidata: 'Q183',
          short_code: 'de',
          text_en: 'Germany',
          language_en: 'en',
          text: 'Germany',
          language: 'en',
          text_de: 'Deutschland',
          language_de: 'de',
          text_fr: 'Allemagne',
          language_fr: 'fr',
          text_nl: 'Duitsland',
          language_nl: 'nl',
          text_it: 'Germania',
          language_it: 'it',
          text_es: 'Alemania',
          language_es: 'es',
          text_pt: 'Alemanha',
          language_pt: 'pt',
          text_pl: 'Niemcy',
          language_pl: 'pl',
          text_ru: 'Германия',
          language_ru: 'ru',
        },
      ],
    },
    {
      id: 'address.1882189389165686',
      type: 'Feature',
      place_type: ['address'],
      relevance: 1,
      properties: {
        accuracy: 'street',
        mapbox_id: 'dXJuOm1ieGFkci1zdHI6Y2EyZjMxNmMtZjBhMy00ZmYwLWEwODgtZDYxMzg4ZmUwNTVh',
      },
      text_en: 'Berlin',
      place_name_en: 'Berlin, 24848 Klein Bennebek, Germany',
      text: 'Berlin',
      place_name: 'Berlin, 24848 Klein Bennebek, Germany',
      text_de: 'Berlin',
      place_name_de: 'Berlin, 24848 Klein Bennebek, Deutschland',
      text_fr: 'Berlin',
      place_name_fr: 'Berlin, 24848 Klein Bennebek, Allemagne',
      text_nl: 'Berlin',
      place_name_nl: 'Berlin, 24848 Klein Bennebek, Duitsland',
      text_it: 'Berlin',
      place_name_it: 'Berlin, 24848 Klein Bennebek, Germania',
      text_es: 'Berlin',
      place_name_es: 'Berlin, 24848 Klein Bennebek, Alemania',
      text_pt: 'Berlin',
      place_name_pt: 'Berlin, 24848 Klein Bennebek, Alemanha',
      text_pl: 'Berlin',
      place_name_pl: 'Berlin, 24848 Klein Bennebek, Niemcy',
      text_ru: 'Berlin',
      place_name_ru: 'Berlin, 24848 Клайн-Беннебек, Германия',
      center: [9.422626, 54.404248],
      geometry: {
        type: 'Point',
        coordinates: [9.422626, 54.404248],
      },
      context: [
        {
          id: 'postcode.13266490',
          mapbox_id: 'dXJuOm1ieHBsYzp5bTQ2',
          text_en: '24848',
          text: '24848',
          text_de: '24848',
          text_fr: '24848',
          text_nl: '24848',
          text_it: '24848',
          text_es: '24848',
          text_pt: '24848',
          text_pl: '24848',
          text_ru: '24848',
        },
        {
          id: 'place.40798266',
          mapbox_id: 'dXJuOm1ieHBsYzpBbTZJT2c',
          wikidata: 'Q556639',
          text_en: 'Klein Bennebek',
          language_en: 'en',
          text: 'Klein Bennebek',
          language: 'en',
          text_de: 'Klein Bennebek',
          language_de: 'de',
          text_fr: 'Klein Bennebek',
          language_fr: 'fr',
          text_nl: 'Klein Bennebek',
          language_nl: 'nl',
          text_it: 'Klein Bennebek',
          language_it: 'it',
          text_es: 'Klein Bennebek',
          language_es: 'es',
          text_pt: 'Klein Bennebek',
          language_pt: 'pt',
          text_pl: 'Klein Bennebek',
          language_pl: 'pl',
          text_ru: 'Клайн-Беннебек',
          language_ru: 'ru',
        },
        {
          id: 'district.1885754',
          mapbox_id: 'dXJuOm1ieHBsYzpITVk2',
          wikidata: 'Q2941',
          text_en: 'Distrito de Schleswig-Flensburg',
          language_en: 'es',
          text: 'Distrito de Schleswig-Flensburg',
          language: 'es',
          text_de: 'Kreis Schleswig-Flensburg',
          language_de: 'de',
          text_fr: 'Kreis Schleswig-Flensburg',
          text_nl: 'Kreis Schleswig-Flensburg',
          text_it: 'Kreis Schleswig-Flensburg',
          text_es: 'Distrito de Schleswig-Flensburg',
          language_es: 'es',
          text_pt: 'Distrito de Schleswig-Flensburg',
          language_pt: 'es',
          text_pl: 'Powiat Schleswig-Flensburg',
          language_pl: 'pl',
          text_ru: 'Шлезвиг-Фленсбург',
          language_ru: 'ru',
        },
        {
          id: 'region.17466',
          mapbox_id: 'dXJuOm1ieHBsYzpSRG8',
          wikidata: 'Q1194',
          short_code: 'DE-SH',
          text_en: 'Schleswig-Holstein',
          language_en: 'en',
          text: 'Schleswig-Holstein',
          language: 'en',
          text_de: 'Schleswig-Holstein',
          language_de: 'de',
          text_fr: 'Schleswig-Holstein',
          language_fr: 'fr',
          text_nl: 'Sleeswijk-Holstein',
          language_nl: 'nl',
          text_it: 'Schleswig-Holstein',
          language_it: 'it',
          text_es: 'Schleswig-Holstein',
          language_es: 'es',
          text_pt: 'Schleswig-Holstein',
          language_pt: 'pt',
          text_pl: 'Szlezwik-Holsztyn',
          language_pl: 'pl',
          text_ru: 'Шлезвиг-Гольштейн',
          language_ru: 'ru',
        },
        {
          id: 'country.8762',
          mapbox_id: 'dXJuOm1ieHBsYzpJam8',
          wikidata: 'Q183',
          short_code: 'de',
          text_en: 'Germany',
          language_en: 'en',
          text: 'Germany',
          language: 'en',
          text_de: 'Deutschland',
          language_de: 'de',
          text_fr: 'Allemagne',
          language_fr: 'fr',
          text_nl: 'Duitsland',
          language_nl: 'nl',
          text_it: 'Germania',
          language_it: 'it',
          text_es: 'Alemania',
          language_es: 'es',
          text_pt: 'Alemanha',
          language_pt: 'pt',
          text_pl: 'Niemcy',
          language_pl: 'pl',
          text_ru: 'Германия',
          language_ru: 'ru',
        },
      ],
    },
    {
      id: 'address.7517935193989996',
      type: 'Feature',
      place_type: ['address'],
      relevance: 0.958333,
      properties: {
        accuracy: 'street',
        mapbox_id: 'dXJuOm1ieGFkci1zdHI6ZTY0MTBlYTgtNzBhZS00MmViLTk0ZWItNThlM2U4YmUzNDcz',
      },
      text_en: 'Barlin',
      place_name_en: 'Barlin, 17159 Dargun, Germany',
      text: 'Barlin',
      place_name: 'Barlin, 17159 Dargun, Germany',
      text_de: 'Barlin',
      place_name_de: 'Barlin, 17159 Dargun, Deutschland',
      text_fr: 'Barlin',
      place_name_fr: 'Barlin, 17159 Dargun, Allemagne',
      text_nl: 'Barlin',
      place_name_nl: 'Barlin, 17159 Dargun, Duitsland',
      text_it: 'Barlin',
      place_name_it: 'Barlin, 17159 Dargun, Germania',
      text_es: 'Barlin',
      place_name_es: 'Barlin, 17159 Dargun, Alemania',
      text_pt: 'Barlin',
      place_name_pt: 'Barlin, 17159 Dargun, Alemanha',
      text_pl: 'Barlin',
      place_name_pl: 'Barlin, 17159 Dargun, Niemcy',
      text_ru: 'Barlin',
      place_name_ru: 'Barlin, 17159 Даргун, Германия',
      center: [12.883232, 53.922631],
      geometry: {
        type: 'Point',
        coordinates: [12.883232, 53.922631],
      },
      context: [
        {
          id: 'postcode.8072762',
          mapbox_id: 'dXJuOm1ieHBsYzpleTQ2',
          text_en: '17159',
          text: '17159',
          text_de: '17159',
          text_fr: '17159',
          text_nl: '17159',
          text_it: '17159',
          text_es: '17159',
          text_pt: '17159',
          text_pl: '17159',
          text_ru: '17159',
        },
        {
          id: 'locality.19302970',
          mapbox_id: 'dXJuOm1ieHBsYzpBU2FLT2c',
          text_en: 'Barlin',
          language_en: 'de',
          text: 'Barlin',
          language: 'de',
          text_de: 'Barlin',
          language_de: 'de',
          text_fr: 'Barlin',
          text_nl: 'Barlin',
          text_it: 'Barlin',
          text_es: 'Barlin',
          text_pt: 'Barlin',
          text_pl: 'Barlin',
          text_ru: 'Barlin',
        },
        {
          id: 'place.14256186',
          mapbox_id: 'dXJuOm1ieHBsYzoyWWc2',
          wikidata: 'Q50959',
          text_en: 'Dargun',
          language_en: 'en',
          text: 'Dargun',
          language: 'en',
          text_de: 'Dargun',
          language_de: 'de',
          text_fr: 'Dargun',
          language_fr: 'fr',
          text_nl: 'Dargun',
          language_nl: 'nl',
          text_it: 'Dargun',
          language_it: 'it',
          text_es: 'Dargun',
          language_es: 'es',
          text_pt: 'Dargun',
          language_pt: 'pt',
          text_pl: 'Dargun',
          language_pl: 'pl',
          text_ru: 'Даргун',
          language_ru: 'ru',
        },
        {
          id: 'district.1214010',
          mapbox_id: 'dXJuOm1ieHBsYzpFb1k2',
          wikidata: 'Q2902',
          text_en: 'Mecklenburgische Seenplatte District',
          language_en: 'en',
          text: 'Mecklenburgische Seenplatte District',
          language: 'en',
          text_de: 'Kreis Mecklenburgische Seenplatte',
          language_de: 'de',
          text_fr: 'Plateau des lacs mecklembourgeois',
          language_fr: 'fr',
          text_nl: 'Landkreis Mecklenburgische Seenplatte',
          language_nl: 'nl',
          text_it: 'circondario della Terra dei Laghi del Meclemburgo',
          language_it: 'it',
          text_es: 'Lagos de Mecklemburgo',
          language_es: 'es',
          text_pt: 'Lagos de Mecklemburgo',
          language_pt: 'es',
          text_pl: 'Landkreis Mecklenburgische Seenplatte',
          language_pl: 'pl',
          text_ru: 'Мекленбург-Зеенплате',
          language_ru: 'ru',
        },
        {
          id: 'region.25658',
          mapbox_id: 'dXJuOm1ieHBsYzpaRG8',
          wikidata: 'Q1196',
          short_code: 'DE-MV',
          text_en: 'Mecklenburg-Western Pomerania',
          language_en: 'en',
          text: 'Mecklenburg-Western Pomerania',
          language: 'en',
          text_de: 'Mecklenburg-Vorpommern',
          language_de: 'de',
          text_fr: 'Mecklembourg-Poméranie-Occidentale',
          language_fr: 'fr',
          text_nl: 'Mecklenburg-Voor-Pommeren',
          language_nl: 'nl',
          text_it: 'Meclemburgo-Pomerania Anteriore',
          language_it: 'it',
          text_es: 'Mecklemburgo-Pomerania Occidental',
          language_es: 'es',
          text_pt: 'Mecklemburgo-Pomerânia Ocidental',
          language_pt: 'pt',
          text_pl: 'Meklemburgia-Pomorze Przednie',
          language_pl: 'pl',
          text_ru: 'Мекленбург — Передняя Померания',
          language_ru: 'ru',
        },
        {
          id: 'country.8762',
          mapbox_id: 'dXJuOm1ieHBsYzpJam8',
          wikidata: 'Q183',
          short_code: 'de',
          text_en: 'Germany',
          language_en: 'en',
          text: 'Germany',
          language: 'en',
          text_de: 'Deutschland',
          language_de: 'de',
          text_fr: 'Allemagne',
          language_fr: 'fr',
          text_nl: 'Duitsland',
          language_nl: 'nl',
          text_it: 'Germania',
          language_it: 'it',
          text_es: 'Alemania',
          language_es: 'es',
          text_pt: 'Alemanha',
          language_pt: 'pt',
          text_pl: 'Niemcy',
          language_pl: 'pl',
          text_ru: 'Германия',
          language_ru: 'ru',
        },
      ],
    },
    {
      id: 'address.4752874377841546',
      type: 'Feature',
      place_type: ['address'],
      relevance: 0.958333,
      properties: {
        accuracy: 'street',
        mapbox_id: 'dXJuOm1ieGFkci1zdHI6ODljMjJmMWItNTUyMy00ODIwLWFiNDYtNjU0YTRiZTc4NzJm',
      },
      text_en: 'Ferliner Straße',
      place_name_en: 'Ferliner Straße, 84332 Hebertsfelden, Germany',
      text: 'Ferliner Straße',
      place_name: 'Ferliner Straße, 84332 Hebertsfelden, Germany',
      text_de: 'Ferliner Straße',
      place_name_de: 'Ferliner Straße, 84332 Hebertsfelden, Deutschland',
      text_fr: 'Ferliner Straße',
      place_name_fr: 'Ferliner Straße, 84332 Hebertsfelden, Allemagne',
      text_nl: 'Ferliner Straße',
      place_name_nl: 'Ferliner Straße, 84332 Hebertsfelden, Duitsland',
      text_it: 'Ferliner Straße',
      place_name_it: 'Ferliner Straße, 84332 Hebertsfelden, Germania',
      text_es: 'Ferliner Straße',
      place_name_es: 'Ferliner Straße, 84332 Hebertsfelden, Alemania',
      text_pt: 'Ferliner Straße',
      place_name_pt: 'Ferliner Straße, 84332 Hebertsfelden, Alemanha',
      text_pl: 'Ferliner Straße',
      place_name_pl: 'Ferliner Straße, 84332 Hebertsfelden, Niemcy',
      text_ru: 'Ferliner Straße',
      place_name_ru: 'Ferliner Straße, 84332 Хебертсфельден, Германия',
      center: [12.81704, 48.43586],
      geometry: {
        type: 'Point',
        coordinates: [12.81704, 48.43586],
      },
      context: [
        {
          id: 'postcode.51138106',
          mapbox_id: 'dXJuOm1ieHBsYzpBd3hPT2c',
          text_en: '84332',
          text: '84332',
          text_de: '84332',
          text_fr: '84332',
          text_nl: '84332',
          text_it: '84332',
          text_es: '84332',
          text_pt: '84332',
          text_pl: '84332',
          text_ru: '84332',
        },
        {
          id: 'locality.267905594',
          mapbox_id: 'dXJuOm1ieHBsYzpEL2ZxT2c',
          text_en: 'Prienbach',
          language_en: 'de',
          text: 'Prienbach',
          language: 'de',
          text_de: 'Prienbach',
          language_de: 'de',
          text_fr: 'Prienbach',
          text_nl: 'Prienbach',
          text_it: 'Prienbach',
          text_es: 'Prienbach',
          text_pt: 'Prienbach',
          text_pl: 'Prienbach',
          text_ru: 'Prienbach',
        },
        {
          id: 'place.31664186',
          mapbox_id: 'dXJuOm1ieHBsYzpBZU1vT2c',
          wikidata: 'Q553780',
          text_en: 'Hebertsfelden',
          language_en: 'en',
          text: 'Hebertsfelden',
          language: 'en',
          text_de: 'Hebertsfelden',
          language_de: 'de',
          text_fr: 'Hebertsfelden',
          language_fr: 'fr',
          text_nl: 'Hebertsfelden',
          language_nl: 'nl',
          text_it: 'Hebertsfelden',
          language_it: 'it',
          text_es: 'Hebertsfelden',
          language_es: 'es',
          text_pt: 'Hebertsfelden',
          language_pt: 'pt',
          text_pl: 'Hebertsfelden',
          language_pl: 'pl',
          text_ru: 'Хебертсфельден',
          language_ru: 'ru',
        },
        {
          id: 'district.1795642',
          mapbox_id: 'dXJuOm1ieHBsYzpHMlk2',
          wikidata: 'Q10477',
          text_en: 'arrondissement de Rottal-Inn',
          language_en: 'fr',
          text: 'arrondissement de Rottal-Inn',
          language: 'fr',
          text_de: 'Kreis Rottal-Inn',
          language_de: 'de',
          text_fr: 'arrondissement de Rottal-Inn',
          language_fr: 'fr',
          text_nl: 'arrondissement de Rottal-Inn',
          language_nl: 'fr',
          text_it: 'Districtul Rottal-Inn',
          language_it: 'ro',
          text_es: 'arrondissement de Rottal-Inn',
          language_es: 'fr',
          text_pt: 'Kreis Rottal-Inn',
          text_pl: 'Powiat Rottal-Inn',
          language_pl: 'pl',
          text_ru: 'Ротталь-Инн',
          language_ru: 'ru',
        },
        {
          id: 'region.123962',
          mapbox_id: 'dXJuOm1ieHBsYzpBZVE2',
          wikidata: 'Q980',
          short_code: 'DE-BY',
          text_en: 'Bavaria',
          language_en: 'en',
          text: 'Bavaria',
          language: 'en',
          text_de: 'Bayern',
          language_de: 'de',
          text_fr: 'Bavière',
          language_fr: 'fr',
          text_nl: 'Beieren',
          language_nl: 'nl',
          text_it: 'Baviera',
          language_it: 'it',
          text_es: 'Baviera',
          language_es: 'es',
          text_pt: 'Baviera',
          language_pt: 'pt',
          text_pl: 'Bawaria',
          language_pl: 'pl',
          text_ru: 'Бавария',
          language_ru: 'ru',
        },
        {
          id: 'country.8762',
          mapbox_id: 'dXJuOm1ieHBsYzpJam8',
          wikidata: 'Q183',
          short_code: 'de',
          text_en: 'Germany',
          language_en: 'en',
          text: 'Germany',
          language: 'en',
          text_de: 'Deutschland',
          language_de: 'de',
          text_fr: 'Allemagne',
          language_fr: 'fr',
          text_nl: 'Duitsland',
          language_nl: 'nl',
          text_it: 'Germania',
          language_it: 'it',
          text_es: 'Alemania',
          language_es: 'es',
          text_pt: 'Alemanha',
          language_pt: 'pt',
          text_pl: 'Niemcy',
          language_pl: 'pl',
          text_ru: 'Германия',
          language_ru: 'ru',
        },
      ],
    },
    {
      id: 'address.7246440478456020',
      type: 'Feature',
      place_type: ['address'],
      relevance: 0.958333,
      properties: {
        accuracy: 'street',
        mapbox_id: 'dXJuOm1ieGFkci1zdHI6MTUyNjZlZjItOTIxZC00OTc0LWIyZmMtOWM2NTQyOWE3MDEx',
      },
      text_en: 'Erlin',
      place_name_en: 'Erlin, 74545 Michelfeld, Germany',
      text: 'Erlin',
      place_name: 'Erlin, 74545 Michelfeld, Germany',
      text_de: 'Erlin',
      place_name_de: 'Erlin, 74545 Michelfeld, Deutschland',
      text_fr: 'Erlin',
      place_name_fr: 'Erlin, 74545 Michelfeld, Allemagne',
      text_nl: 'Erlin',
      place_name_nl: 'Erlin, 74545 Michelfeld, Duitsland',
      text_it: 'Erlin',
      place_name_it: 'Erlin, 74545 Michelfeld, Germania',
      text_es: 'Erlin',
      place_name_es: 'Erlin, 74545 Michelfeld, Alemania',
      text_pt: 'Erlin',
      place_name_pt: 'Erlin, 74545 Michelfeld, Alemanha',
      text_pl: 'Erlin',
      place_name_pl: 'Erlin, 74545 Michelfeld, Niemcy',
      text_ru: 'Erlin',
      place_name_ru: 'Erlin, 74545 Михельфельд, Германия',
      center: [9.658099, 49.105636],
      geometry: {
        type: 'Point',
        coordinates: [9.658099, 49.105636],
      },
      context: [
        {
          id: 'postcode.43716154',
          mapbox_id: 'dXJuOm1ieHBsYzpBcHNPT2c',
          text_en: '74545',
          text: '74545',
          text_de: '74545',
          text_fr: '74545',
          text_nl: '74545',
          text_it: '74545',
          text_es: '74545',
          text_pt: '74545',
          text_pl: '74545',
          text_ru: '74545',
        },
        {
          id: 'locality.166046266',
          mapbox_id: 'dXJuOm1ieHBsYzpDZVdxT2c',
          text_en: 'Kiesberg',
          language_en: 'de',
          text: 'Kiesberg',
          language: 'de',
          text_de: 'Kiesberg',
          language_de: 'de',
          text_fr: 'Kiesberg',
          text_nl: 'Kiesberg',
          text_it: 'Kiesberg',
          text_es: 'Kiesberg',
          text_pt: 'Kiesberg',
          text_pl: 'Kiesberg',
          text_ru: 'Kiesberg',
        },
        {
          id: 'place.50980922',
          mapbox_id: 'dXJuOm1ieHBsYzpBd25vT2c',
          wikidata: 'Q81048',
          text_en: 'Michelfeld',
          language_en: 'en',
          text: 'Michelfeld',
          language: 'en',
          text_de: 'Michelfeld',
          language_de: 'de',
          text_fr: 'Michelfeld',
          language_fr: 'fr',
          text_nl: 'Michelfeld',
          language_nl: 'nl',
          text_it: 'Michelfeld',
          language_it: 'it',
          text_es: 'Michelfeld',
          language_es: 'es',
          text_pt: 'Michelfeld',
          language_pt: 'pt',
          text_pl: 'Michelfeld',
          language_pl: 'pl',
          text_ru: 'Михельфельд',
          language_ru: 'ru',
        },
        {
          id: 'district.1902138',
          mapbox_id: 'dXJuOm1ieHBsYzpIUVk2',
          wikidata: 'Q8520',
          text_en: 'Landkreis Schwäbisch Hall',
          language_en: 'en',
          text: 'Landkreis Schwäbisch Hall',
          language: 'en',
          text_de: 'Kreis Schwäbisch Hall',
          language_de: 'de',
          text_fr: 'arrondissement de Schwäbisch Hall',
          language_fr: 'fr',
          text_nl: 'arrondissement de Schwäbisch Hall',
          language_nl: 'fr',
          text_it: 'circondario di Schwäbisch Hall',
          language_it: 'it',
          text_es: 'arrondissement de Schwäbisch Hall',
          language_es: 'fr',
          text_pt: 'circondario di Schwäbisch Hall',
          language_pt: 'it',
          text_pl: 'Districtul Schwäbisch Hall',
          language_pl: 'ro',
          text_ru: 'Швебиш-Халль',
          language_ru: 'ru',
        },
        {
          id: 'region.132154',
          mapbox_id: 'dXJuOm1ieHBsYzpBZ1E2',
          wikidata: 'Q985',
          short_code: 'DE-BW',
          text_en: 'Baden-Württemberg',
          language_en: 'en',
          text: 'Baden-Württemberg',
          language: 'en',
          text_de: 'Baden-Württemberg',
          language_de: 'de',
          text_fr: 'Bade-Wurtemberg',
          language_fr: 'fr',
          text_nl: 'Baden-Württemberg',
          language_nl: 'nl',
          text_it: 'Baden-Württemberg',
          language_it: 'it',
          text_es: 'Baden-Wurtemberg',
          language_es: 'es',
          text_pt: 'Baden-Württemberg',
          language_pt: 'pt',
          text_pl: 'Badenia-Wirtembergia',
          language_pl: 'pl',
          text_ru: 'Баден-Вюртемберг',
          language_ru: 'ru',
        },
        {
          id: 'country.8762',
          mapbox_id: 'dXJuOm1ieHBsYzpJam8',
          wikidata: 'Q183',
          short_code: 'de',
          text_en: 'Germany',
          language_en: 'en',
          text: 'Germany',
          language: 'en',
          text_de: 'Deutschland',
          language_de: 'de',
          text_fr: 'Allemagne',
          language_fr: 'fr',
          text_nl: 'Duitsland',
          language_nl: 'nl',
          text_it: 'Germania',
          language_it: 'it',
          text_es: 'Alemania',
          language_es: 'es',
          text_pt: 'Alemanha',
          language_pt: 'pt',
          text_pl: 'Niemcy',
          language_pl: 'pl',
          text_ru: 'Германия',
          language_ru: 'ru',
        },
      ],
    },
  ],
  attribution:
    'NOTICE: © 2025 Mapbox and its suppliers. All rights reserved. Use of this data is subject to the Mapbox Terms of Service (https://www.mapbox.com/about/maps/). This response and the information it contains may not be retained.',
}
