export const berlinDe = {
  type: 'FeatureCollection',
  query: ['berlin'],
  features: [
    {
      id: 'place.115770',
      type: 'Feature',
      place_type: ['region', 'place'],
      relevance: 1,
      properties: {
        mapbox_id: 'dXJuOm1ieHBsYzpBY1E2',
        wikidata: 'Q64',
        short_code: 'DE-BE',
      },
      text_de: 'Berlin',
      language_de: 'de',
      place_name_de: 'Berlin, Deutschland',
      text: 'Berlin',
      language: 'de',
      place_name: 'Berlin, Deutschland',
      bbox: [13.08836, 52.338261, 13.760906, 52.675502],
      center: [13.38886, 52.517037],
      geometry: {
        type: 'Point',
        coordinates: [13.38886, 52.517037],
      },
      context: [
        {
          id: 'country.8762',
          mapbox_id: 'dXJuOm1ieHBsYzpJam8',
          wikidata: 'Q183',
          short_code: 'de',
          text_de: 'Deutschland',
          language_de: 'de',
          text: 'Deutschland',
          language: 'de',
        },
      ],
    },
    {
      id: 'place.25995500',
      type: 'Feature',
      place_type: ['place'],
      relevance: 1,
      properties: {
        mapbox_id: 'dXJuOm1ieHBsYzpBWXlvN0E',
        wikidata: 'Q614184',
      },
      text_de: 'Berlin',
      language_de: 'de',
      place_name_de: 'Berlin, Maryland, Vereinigte Staaten',
      text: 'Berlin',
      language: 'de',
      place_name: 'Berlin, Maryland, Vereinigte Staaten',
      bbox: [-75.364989, 38.141747, -75.087625, 38.4078],
      center: [-75.219004, 38.324728],
      geometry: {
        type: 'Point',
        coordinates: [-75.219004, 38.324728],
      },
      context: [
        {
          id: 'district.25396972',
          mapbox_id: 'dXJuOm1ieHBsYzpBWU9HN0E',
          wikidata: 'Q494072',
          text_de: 'Worcester County',
          language_de: 'de',
          text: 'Worcester County',
          language: 'de',
        },
        {
          id: 'region.124140',
          mapbox_id: 'dXJuOm1ieHBsYzpBZVRz',
          wikidata: 'Q1391',
          short_code: 'US-MD',
          text_de: 'Maryland',
          language_de: 'de',
          text: 'Maryland',
          language: 'de',
        },
        {
          id: 'country.8940',
          mapbox_id: 'dXJuOm1ieHBsYzpJdXc',
          wikidata: 'Q30',
          short_code: 'us',
          text_de: 'Vereinigte Staaten',
          language_de: 'de',
          text: 'Vereinigte Staaten',
          language: 'de',
        },
      ],
    },
    {
      id: 'place.25970924',
      type: 'Feature',
      place_type: ['place'],
      relevance: 1,
      properties: {
        mapbox_id: 'dXJuOm1ieHBsYzpBWXhJN0E',
        wikidata: 'Q1086827',
      },
      text_de: 'Berlin',
      language_de: 'de',
      place_name_de: 'Berlin, New Jersey, Vereinigte Staaten',
      text: 'Berlin',
      language: 'de',
      place_name: 'Berlin, New Jersey, Vereinigte Staaten',
      bbox: [-74.974491, 39.70904, -74.878605, 39.809363],
      center: [-74.929456, 39.791432],
      geometry: {
        type: 'Point',
        coordinates: [-74.929456, 39.791432],
      },
      context: [
        {
          id: 'district.3016428',
          mapbox_id: 'dXJuOm1ieHBsYzpMZ2Jz',
          wikidata: 'Q497810',
          text_de: 'Camden County',
          language_de: 'de',
          text: 'Camden County',
          language: 'de',
        },
        {
          id: 'region.156908',
          mapbox_id: 'dXJuOm1ieHBsYzpBbVRz',
          wikidata: 'Q1408',
          short_code: 'US-NJ',
          text_de: 'New Jersey',
          language_de: 'de',
          text: 'New Jersey',
          language: 'de',
        },
        {
          id: 'country.8940',
          mapbox_id: 'dXJuOm1ieHBsYzpJdXc',
          wikidata: 'Q30',
          short_code: 'us',
          text_de: 'Vereinigte Staaten',
          language_de: 'de',
          text: 'Vereinigte Staaten',
          language: 'de',
        },
      ],
    },
    {
      id: 'place.26118380',
      type: 'Feature',
      place_type: ['place'],
      relevance: 1,
      properties: {
        mapbox_id: 'dXJuOm1ieHBsYzpBWTZJN0E',
        wikidata: 'Q2219095',
      },
      text_de: 'Berlin Heights',
      language_de: 'de',
      place_name_de: 'Berlin Heights, Ohio, Vereinigte Staaten',
      text: 'Berlin Heights',
      language: 'de',
      place_name: 'Berlin Heights, Ohio, Vereinigte Staaten',
      bbox: [-82.54353, 41.285345, -82.382139, 41.364821],
      center: [-82.493433, 41.325154],
      geometry: {
        type: 'Point',
        coordinates: [-82.493433, 41.325154],
      },
      context: [
        {
          id: 'district.7235308',
          mapbox_id: 'dXJuOm1ieHBsYzpibWJz',
          wikidata: 'Q111310',
          text_de: 'Erie County',
          language_de: 'de',
          text: 'Erie County',
          language: 'de',
        },
        {
          id: 'region.140524',
          mapbox_id: 'dXJuOm1ieHBsYzpBaVRz',
          wikidata: 'Q1397',
          short_code: 'US-OH',
          text_de: 'Ohio',
          language_de: 'de',
          text: 'Ohio',
          language: 'de',
        },
        {
          id: 'country.8940',
          mapbox_id: 'dXJuOm1ieHBsYzpJdXc',
          wikidata: 'Q30',
          short_code: 'us',
          text_de: 'Vereinigte Staaten',
          language_de: 'de',
          text: 'Vereinigte Staaten',
          language: 'de',
        },
      ],
    },
    {
      id: 'place.26044652',
      type: 'Feature',
      place_type: ['place'],
      relevance: 1,
      properties: {
        mapbox_id: 'dXJuOm1ieHBsYzpBWTFvN0E',
        wikidata: 'Q524646',
      },
      text_de: 'Berlin',
      language_de: 'de',
      place_name_de: 'Berlin, Massachusetts, Vereinigte Staaten',
      text: 'Berlin',
      language: 'de',
      place_name: 'Berlin, Massachusetts, Vereinigte Staaten',
      bbox: [-71.678766, 42.350413, -71.58015, 42.418232],
      center: [-71.638302, 42.381333],
      geometry: {
        type: 'Point',
        coordinates: [-71.638302, 42.381333],
      },
      context: [
        {
          id: 'district.25405164',
          mapbox_id: 'dXJuOm1ieHBsYzpBWU9tN0E',
          wikidata: 'Q54093',
          text_de: 'Worcester County',
          language_de: 'de',
          text: 'Worcester County',
          language: 'de',
        },
        {
          id: 'region.353516',
          mapbox_id: 'dXJuOm1ieHBsYzpCV1Rz',
          wikidata: 'Q771',
          short_code: 'US-MA',
          text_de: 'Massachusetts',
          language_de: 'de',
          text: 'Massachusetts',
          language: 'de',
        },
        {
          id: 'country.8940',
          mapbox_id: 'dXJuOm1ieHBsYzpJdXc',
          wikidata: 'Q30',
          short_code: 'us',
          text_de: 'Vereinigte Staaten',
          language_de: 'de',
          text: 'Vereinigte Staaten',
          language: 'de',
        },
      ],
    },
  ],
  attribution:
    'NOTICE: © 2025 Mapbox and its suppliers. All rights reserved. Use of this data is subject to the Mapbox Terms of Service (https://www.mapbox.com/about/maps/). This response and the information it contains may not be retained.',
}
