export const hamburgNY = {
  type: 'FeatureCollection',
  query: ['hamburg', 'new', 'jersey'],
  features: [
    {
      id: 'place.138242284',
      type: 'Feature',
      place_type: ['place'],
      relevance: 1,
      properties: {
        mapbox_id: 'dXJuOm1ieHBsYzpDRDFvN0E',
        wikidata: 'Q1082931',
      },
      text_en: 'Hamburg',
      language_en: 'en',
      place_name_en: 'Hamburg, New Jersey, United States',
      text: 'Hamburg',
      language: 'en',
      place_name: 'Hamburg, New Jersey, United States',
      text_de: 'Hamburg',
      language_de: 'de',
      place_name_de: 'Hamburg, New Jersey, Vereinigte Staaten',
      text_fr: 'Hamburg',
      language_fr: 'fr',
      place_name_fr: 'Hamburg, New Jersey, États-Unis',
      text_nl: 'Hamburg',
      language_nl: 'nl',
      place_name_nl: 'Hamburg, New Jersey, Verenigde Staten van Amerika',
      text_it: 'Hamburg',
      language_it: 'it',
      place_name_it: "Hamburg, New Jersey, Stati Uniti d'America",
      text_es: 'Hamburg',
      language_es: 'es',
      place_name_es: 'Hamburg, Nueva Jersey, Estados Unidos',
      text_pt: 'Hamburg',
      language_pt: 'pt',
      place_name_pt: 'Hamburg, Nova Jérsia, Estados Unidos',
      text_pl: 'Hamburg',
      language_pl: 'nl',
      place_name_pl: 'Hamburg, New Jersey, Stany Zjednoczone',
      text_ru: 'Хамбург',
      language_ru: 'kk',
      place_name_ru: 'Хамбург, Нью-Джерси, США',
      bbox: [-74.632296, 41.101134, -74.510997, 41.194008],
      center: [-74.576227, 41.153431],
      geometry: {
        type: 'Point',
        coordinates: [-74.576227, 41.153431],
      },
      context: [
        {
          id: 'district.22456044',
          mapbox_id: 'dXJuOm1ieHBsYzpBVmFtN0E',
          wikidata: 'Q495998',
          text_en: 'Sussex County',
          language_en: 'en',
          text: 'Sussex County',
          language: 'en',
          text_de: 'Sussex County',
          language_de: 'de',
          text_fr: 'comté de Sussex',
          language_fr: 'fr',
          text_nl: 'Sussex County',
          language_nl: 'nl',
          text_it: 'contea di Sussex',
          language_it: 'it',
          text_es: 'Condado de Sussex',
          language_es: 'es',
          text_pt: 'Condado de Sussex',
          language_pt: 'pt',
          text_pl: 'Hrabstwo Sussex',
          language_pl: 'pl',
          text_ru: 'Сассекс',
          language_ru: 'ru',
        },
        {
          id: 'region.156908',
          mapbox_id: 'dXJuOm1ieHBsYzpBbVRz',
          wikidata: 'Q1408',
          short_code: 'US-NJ',
          text_en: 'New Jersey',
          language_en: 'en',
          text: 'New Jersey',
          language: 'en',
          text_de: 'New Jersey',
          language_de: 'de',
          text_fr: 'New Jersey',
          language_fr: 'fr',
          text_nl: 'New Jersey',
          language_nl: 'nl',
          text_it: 'New Jersey',
          language_it: 'it',
          text_es: 'Nueva Jersey',
          language_es: 'es',
          text_pt: 'Nova Jérsia',
          language_pt: 'pt',
          text_pl: 'New Jersey',
          language_pl: 'pl',
          text_ru: 'Нью-Джерси',
          language_ru: 'ru',
        },
        {
          id: 'country.8940',
          mapbox_id: 'dXJuOm1ieHBsYzpJdXc',
          wikidata: 'Q30',
          short_code: 'us',
          text_en: 'United States',
          language_en: 'en',
          text: 'United States',
          language: 'en',
          text_de: 'Vereinigte Staaten',
          language_de: 'de',
          text_fr: 'États-Unis',
          language_fr: 'fr',
          text_nl: 'Verenigde Staten van Amerika',
          language_nl: 'nl',
          text_it: "Stati Uniti d'America",
          language_it: 'it',
          text_es: 'Estados Unidos',
          language_es: 'es',
          text_pt: 'Estados Unidos',
          language_pt: 'pt',
          text_pl: 'Stany Zjednoczone',
          language_pl: 'pl',
          text_ru: 'США',
          language_ru: 'ru',
        },
      ],
    },
    {
      id: 'address.4892302912777302',
      type: 'Feature',
      place_type: ['address'],
      relevance: 1,
      properties: {
        accuracy: 'street',
        'override:postcode': '',
        mapbox_id: 'dXJuOm1ieGFkci1zdHI6YTVmNjA1ZDItOGJhYS00MWRlLWE0MmUtYzYzYThjY2JlYzE2',
      },
      text_en: 'Hamburg Turnpike',
      place_name_en: 'Hamburg Turnpike, Stockholm, New Jersey 07460, United States',
      text: 'Hamburg Turnpike',
      place_name: 'Hamburg Turnpike, Stockholm, New Jersey 07460, United States',
      text_de: 'Hamburg Turnpike',
      place_name_de: 'Hamburg Turnpike, Stockholm, New Jersey 07460, Vereinigte Staaten',
      text_fr: 'Hamburg Turnpike',
      place_name_fr: 'Hamburg Turnpike, Stockholm, New Jersey 07460, États-Unis',
      text_nl: 'Hamburg Turnpike',
      place_name_nl: 'Hamburg Turnpike, Stockholm, New Jersey 07460, Verenigde Staten van Amerika',
      text_it: 'Hamburg Turnpike',
      place_name_it: "Hamburg Turnpike, Stockholm, New Jersey 07460, Stati Uniti d'America",
      text_es: 'Hamburg Turnpike',
      place_name_es: 'Hamburg Turnpike, Stockholm, Nueva Jersey 07460, Estados Unidos',
      text_pt: 'Hamburg Turnpike',
      place_name_pt: 'Hamburg Turnpike, Stockholm, Nova Jérsia 07460, Estados Unidos',
      text_pl: 'Hamburg Turnpike',
      place_name_pl: 'Hamburg Turnpike, Stockholm, New Jersey 07460, Stany Zjednoczone',
      text_ru: 'Hamburg Turnpike',
      place_name_ru: 'Hamburg Turnpike, Stockholm, Нью-Джерси 07460, США',
      center: [-74.52295, 41.11971],
      geometry: {
        type: 'Point',
        coordinates: [-74.52295, 41.11971],
      },
      context: [
        {
          id: 'postcode.20008684',
          mapbox_id: 'dXJuOm1ieHBsYzpBVEZPN0E',
          text_en: '07460',
          text: '07460',
          text_de: '07460',
          text_fr: '07460',
          text_nl: '07460',
          text_it: '07460',
          text_es: '07460',
          text_pt: '07460',
          text_pl: '07460',
          text_ru: '07460',
        },
        {
          id: 'locality.237284076',
          mapbox_id: 'dXJuOm1ieHBsYzpEaVNxN0E',
          text_en: 'Hardyston Township',
          language_en: 'en',
          text: 'Hardyston Township',
          language: 'en',
          text_de: 'Hardyston Township',
          language_de: 'en',
          text_fr: 'Hardyston Township',
          language_fr: 'en',
          text_nl: 'Hardyston Township',
          language_nl: 'en',
          text_it: 'Hardyston Township',
          language_it: 'en',
          text_es: 'Hardyston Township',
          language_es: 'en',
          text_pt: 'Hardyston Township',
          text_pl: 'Hardyston Township',
          language_pl: 'en',
          text_ru: 'Hardyston Township',
        },
        {
          id: 'place.315435244',
          mapbox_id: 'dXJuOm1ieHBsYzpFczBvN0E',
          wikidata: 'Q7617988',
          text_en: 'Stockholm',
          language_en: 'en',
          text: 'Stockholm',
          language: 'en',
          text_de: 'Stockholm',
          language_de: 'en',
          text_fr: 'Stockholm',
          language_fr: 'fr',
          text_nl: 'Stockholm',
          language_nl: 'fr',
          text_it: 'Stockholm',
          language_it: 'fr',
          text_es: 'Stockholm',
          language_es: 'fr',
          text_pt: 'Stockholm',
          text_pl: 'Stockholm',
          language_pl: 'en',
          text_ru: 'Stockholm',
        },
        {
          id: 'district.22456044',
          mapbox_id: 'dXJuOm1ieHBsYzpBVmFtN0E',
          wikidata: 'Q495998',
          text_en: 'Sussex County',
          language_en: 'en',
          text: 'Sussex County',
          language: 'en',
          text_de: 'Sussex County',
          language_de: 'de',
          text_fr: 'comté de Sussex',
          language_fr: 'fr',
          text_nl: 'Sussex County',
          language_nl: 'nl',
          text_it: 'contea di Sussex',
          language_it: 'it',
          text_es: 'Condado de Sussex',
          language_es: 'es',
          text_pt: 'Condado de Sussex',
          language_pt: 'pt',
          text_pl: 'Hrabstwo Sussex',
          language_pl: 'pl',
          text_ru: 'Сассекс',
          language_ru: 'ru',
        },
        {
          id: 'region.156908',
          mapbox_id: 'dXJuOm1ieHBsYzpBbVRz',
          wikidata: 'Q1408',
          short_code: 'US-NJ',
          text_en: 'New Jersey',
          language_en: 'en',
          text: 'New Jersey',
          language: 'en',
          text_de: 'New Jersey',
          language_de: 'de',
          text_fr: 'New Jersey',
          language_fr: 'fr',
          text_nl: 'New Jersey',
          language_nl: 'nl',
          text_it: 'New Jersey',
          language_it: 'it',
          text_es: 'Nueva Jersey',
          language_es: 'es',
          text_pt: 'Nova Jérsia',
          language_pt: 'pt',
          text_pl: 'New Jersey',
          language_pl: 'pl',
          text_ru: 'Нью-Джерси',
          language_ru: 'ru',
        },
        {
          id: 'country.8940',
          mapbox_id: 'dXJuOm1ieHBsYzpJdXc',
          wikidata: 'Q30',
          short_code: 'us',
          text_en: 'United States',
          language_en: 'en',
          text: 'United States',
          language: 'en',
          text_de: 'Vereinigte Staaten',
          language_de: 'de',
          text_fr: 'États-Unis',
          language_fr: 'fr',
          text_nl: 'Verenigde Staten van Amerika',
          language_nl: 'nl',
          text_it: "Stati Uniti d'America",
          language_it: 'it',
          text_es: 'Estados Unidos',
          language_es: 'es',
          text_pt: 'Estados Unidos',
          language_pt: 'pt',
          text_pl: 'Stany Zjednoczone',
          language_pl: 'pl',
          text_ru: 'США',
          language_ru: 'ru',
        },
      ],
    },
    {
      id: 'address.5578007523305814',
      type: 'Feature',
      place_type: ['address'],
      relevance: 1,
      properties: {
        accuracy: 'street',
        mapbox_id: 'dXJuOm1ieGFkci1zdHI6YTY5NzVmZjAtMWI1MC00ZTZlLTlkNTctZTIzYWQ3N2Y5NGU5',
      },
      text_en: 'Hamburg Pike',
      place_name_en: 'Hamburg Pike, Hamburg, New Jersey 07419, United States',
      text: 'Hamburg Pike',
      place_name: 'Hamburg Pike, Hamburg, New Jersey 07419, United States',
      text_de: 'Hamburg Pike',
      place_name_de: 'Hamburg Pike, Hamburg, New Jersey 07419, Vereinigte Staaten',
      text_fr: 'Hamburg Pike',
      place_name_fr: 'Hamburg Pike, Hamburg, New Jersey 07419, États-Unis',
      text_nl: 'Hamburg Pike',
      place_name_nl: 'Hamburg Pike, Hamburg, New Jersey 07419, Verenigde Staten van Amerika',
      text_it: 'Hamburg Pike',
      place_name_it: "Hamburg Pike, Hamburg, New Jersey 07419, Stati Uniti d'America",
      text_es: 'Hamburg Pike',
      place_name_es: 'Hamburg Pike, Hamburg, Nueva Jersey 07419, Estados Unidos',
      text_pt: 'Hamburg Pike',
      place_name_pt: 'Hamburg Pike, Hamburg, Nova Jérsia 07419, Estados Unidos',
      text_pl: 'Hamburg Pike',
      place_name_pl: 'Hamburg Pike, Hamburg, New Jersey 07419, Stany Zjednoczone',
      text_ru: 'Hamburg Pike',
      place_name_ru: 'Hamburg Pike, Хамбург, Нью-Джерси 07419, США',
      center: [-74.541928, 41.125463],
      geometry: {
        type: 'Point',
        coordinates: [-74.541928, 41.125463],
      },
      context: [
        {
          id: 'postcode.19820268',
          mapbox_id: 'dXJuOm1ieHBsYzpBUzV1N0E',
          text_en: '07419',
          text: '07419',
          text_de: '07419',
          text_fr: '07419',
          text_nl: '07419',
          text_it: '07419',
          text_es: '07419',
          text_pt: '07419',
          text_pl: '07419',
          text_ru: '07419',
        },
        {
          id: 'locality.237284076',
          mapbox_id: 'dXJuOm1ieHBsYzpEaVNxN0E',
          text_en: 'Hardyston Township',
          language_en: 'en',
          text: 'Hardyston Township',
          language: 'en',
          text_de: 'Hardyston Township',
          language_de: 'en',
          text_fr: 'Hardyston Township',
          language_fr: 'en',
          text_nl: 'Hardyston Township',
          language_nl: 'en',
          text_it: 'Hardyston Township',
          language_it: 'en',
          text_es: 'Hardyston Township',
          language_es: 'en',
          text_pt: 'Hardyston Township',
          text_pl: 'Hardyston Township',
          language_pl: 'en',
          text_ru: 'Hardyston Township',
        },
        {
          id: 'place.138242284',
          mapbox_id: 'dXJuOm1ieHBsYzpDRDFvN0E',
          wikidata: 'Q1082931',
          text_en: 'Hamburg',
          language_en: 'en',
          text: 'Hamburg',
          language: 'en',
          text_de: 'Hamburg',
          language_de: 'de',
          text_fr: 'Hamburg',
          language_fr: 'fr',
          text_nl: 'Hamburg',
          language_nl: 'nl',
          text_it: 'Hamburg',
          language_it: 'it',
          text_es: 'Hamburg',
          language_es: 'es',
          text_pt: 'Hamburg',
          language_pt: 'pt',
          text_pl: 'Hamburg',
          language_pl: 'nl',
          text_ru: 'Хамбург',
          language_ru: 'kk',
        },
        {
          id: 'district.22456044',
          mapbox_id: 'dXJuOm1ieHBsYzpBVmFtN0E',
          wikidata: 'Q495998',
          text_en: 'Sussex County',
          language_en: 'en',
          text: 'Sussex County',
          language: 'en',
          text_de: 'Sussex County',
          language_de: 'de',
          text_fr: 'comté de Sussex',
          language_fr: 'fr',
          text_nl: 'Sussex County',
          language_nl: 'nl',
          text_it: 'contea di Sussex',
          language_it: 'it',
          text_es: 'Condado de Sussex',
          language_es: 'es',
          text_pt: 'Condado de Sussex',
          language_pt: 'pt',
          text_pl: 'Hrabstwo Sussex',
          language_pl: 'pl',
          text_ru: 'Сассекс',
          language_ru: 'ru',
        },
        {
          id: 'region.156908',
          mapbox_id: 'dXJuOm1ieHBsYzpBbVRz',
          wikidata: 'Q1408',
          short_code: 'US-NJ',
          text_en: 'New Jersey',
          language_en: 'en',
          text: 'New Jersey',
          language: 'en',
          text_de: 'New Jersey',
          language_de: 'de',
          text_fr: 'New Jersey',
          language_fr: 'fr',
          text_nl: 'New Jersey',
          language_nl: 'nl',
          text_it: 'New Jersey',
          language_it: 'it',
          text_es: 'Nueva Jersey',
          language_es: 'es',
          text_pt: 'Nova Jérsia',
          language_pt: 'pt',
          text_pl: 'New Jersey',
          language_pl: 'pl',
          text_ru: 'Нью-Джерси',
          language_ru: 'ru',
        },
        {
          id: 'country.8940',
          mapbox_id: 'dXJuOm1ieHBsYzpJdXc',
          wikidata: 'Q30',
          short_code: 'us',
          text_en: 'United States',
          language_en: 'en',
          text: 'United States',
          language: 'en',
          text_de: 'Vereinigte Staaten',
          language_de: 'de',
          text_fr: 'États-Unis',
          language_fr: 'fr',
          text_nl: 'Verenigde Staten van Amerika',
          language_nl: 'nl',
          text_it: "Stati Uniti d'America",
          language_it: 'it',
          text_es: 'Estados Unidos',
          language_es: 'es',
          text_pt: 'Estados Unidos',
          language_pt: 'pt',
          text_pl: 'Stany Zjednoczone',
          language_pl: 'pl',
          text_ru: 'США',
          language_ru: 'ru',
        },
      ],
    },
    {
      id: 'address.4994460186306076',
      type: 'Feature',
      place_type: ['address'],
      relevance: 0.914815,
      properties: {
        accuracy: 'street',
        mapbox_id: 'dXJuOm1ieGFkci1zdHI6MzIyNTIzODItMTM4My00YjAyLThiNTUtOTAwMGFiMDNiYmQy',
      },
      text_en: 'Hamburg Road',
      place_name_en: 'Hamburg Road, Parsippany, New Jersey 07054, United States',
      text: 'Hamburg Road',
      place_name: 'Hamburg Road, Parsippany, New Jersey 07054, United States',
      text_de: 'Hamburg Road',
      place_name_de:
        'Hamburg Road, Parsippany-Troy Hills Township, New Jersey 07054, Vereinigte Staaten',
      text_fr: 'Hamburg Road',
      place_name_fr: 'Hamburg Road, Parsippany-Troy Hills, New Jersey 07054, États-Unis',
      text_nl: 'Hamburg Road',
      place_name_nl:
        'Hamburg Road, Parsippany-Troy Hills, New Jersey 07054, Verenigde Staten van Amerika',
      text_it: 'Hamburg Road',
      place_name_it: "Hamburg Road, Parsippany-Troy Hills, New Jersey 07054, Stati Uniti d'America",
      text_es: 'Hamburg Road',
      place_name_es: 'Hamburg Road, Parsippany-Troy Hills, Nueva Jersey 07054, Estados Unidos',
      text_pt: 'Hamburg Road',
      place_name_pt: 'Hamburg Road, Parsippany-Troy Hills, Nova Jérsia 07054, Estados Unidos',
      text_pl: 'Hamburg Road',
      place_name_pl: 'Hamburg Road, Parsippany-Troy Hills, New Jersey 07054, Stany Zjednoczone',
      text_ru: 'Hamburg Road',
      place_name_ru: 'Hamburg Road, Парсиппани-Трой-Хилс, Нью-Джерси 07054, США',
      center: [-74.436622, 40.859052],
      geometry: {
        type: 'Point',
        coordinates: [-74.436622, 40.859052],
      },
      context: [
        {
          id: 'postcode.19074796',
          mapbox_id: 'dXJuOm1ieHBsYzpBU01PN0E',
          text_en: '07054',
          text: '07054',
          text_de: '07054',
          text_fr: '07054',
          text_nl: '07054',
          text_it: '07054',
          text_es: '07054',
          text_pt: '07054',
          text_pl: '07054',
          text_ru: '07054',
        },
        {
          id: 'place.252618988',
          mapbox_id: 'dXJuOm1ieHBsYzpEdzZvN0E',
          wikidata: 'Q532344',
          text_en: 'Parsippany',
          language_en: 'en',
          text: 'Parsippany',
          language: 'en',
          text_de: 'Parsippany-Troy Hills Township',
          language_de: 'de',
          text_fr: 'Parsippany-Troy Hills',
          language_fr: 'fr',
          text_nl: 'Parsippany-Troy Hills',
          language_nl: 'nl',
          text_it: 'Parsippany-Troy Hills',
          language_it: 'it',
          text_es: 'Parsippany-Troy Hills',
          language_es: 'es',
          text_pt: 'Parsippany-Troy Hills',
          language_pt: 'es',
          text_pl: 'Parsippany-Troy Hills',
          language_pl: 'nl',
          text_ru: 'Парсиппани-Трой-Хилс',
          language_ru: 'ru',
        },
        {
          id: 'district.16525036',
          mapbox_id: 'dXJuOm1ieHBsYzovQ2Jz',
          wikidata: 'Q498163',
          text_en: 'Morris County',
          language_en: 'en',
          text: 'Morris County',
          language: 'en',
          text_de: 'Morris County',
          language_de: 'de',
          text_fr: 'comté de Morris',
          language_fr: 'fr',
          text_nl: 'Morris County',
          language_nl: 'nl',
          text_it: 'contea di Morris',
          language_it: 'it',
          text_es: 'Condado de Morris',
          language_es: 'es',
          text_pt: 'Condado de Morris',
          language_pt: 'pt',
          text_pl: 'Hrabstwo Morris',
          language_pl: 'pl',
          text_ru: 'Моррис',
          language_ru: 'ru',
        },
        {
          id: 'region.156908',
          mapbox_id: 'dXJuOm1ieHBsYzpBbVRz',
          wikidata: 'Q1408',
          short_code: 'US-NJ',
          text_en: 'New Jersey',
          language_en: 'en',
          text: 'New Jersey',
          language: 'en',
          text_de: 'New Jersey',
          language_de: 'de',
          text_fr: 'New Jersey',
          language_fr: 'fr',
          text_nl: 'New Jersey',
          language_nl: 'nl',
          text_it: 'New Jersey',
          language_it: 'it',
          text_es: 'Nueva Jersey',
          language_es: 'es',
          text_pt: 'Nova Jérsia',
          language_pt: 'pt',
          text_pl: 'New Jersey',
          language_pl: 'pl',
          text_ru: 'Нью-Джерси',
          language_ru: 'ru',
        },
        {
          id: 'country.8940',
          mapbox_id: 'dXJuOm1ieHBsYzpJdXc',
          wikidata: 'Q30',
          short_code: 'us',
          text_en: 'United States',
          language_en: 'en',
          text: 'United States',
          language: 'en',
          text_de: 'Vereinigte Staaten',
          language_de: 'de',
          text_fr: 'États-Unis',
          language_fr: 'fr',
          text_nl: 'Verenigde Staten van Amerika',
          language_nl: 'nl',
          text_it: "Stati Uniti d'America",
          language_it: 'it',
          text_es: 'Estados Unidos',
          language_es: 'es',
          text_pt: 'Estados Unidos',
          language_pt: 'pt',
          text_pl: 'Stany Zjednoczone',
          language_pl: 'pl',
          text_ru: 'США',
          language_ru: 'ru',
        },
      ],
    },
    {
      id: 'address.7206046822993882',
      type: 'Feature',
      place_type: ['address'],
      relevance: 0.914815,
      properties: {
        accuracy: 'street',
        mapbox_id: 'dXJuOm1ieGFkci1zdHI6OGNiMjYzOWMtZDAxYS00OWY3LThmNTEtZTllMmJjMDY4MWU2',
      },
      text_en: 'Hamburg Avenue',
      place_name_en: 'Hamburg Avenue, Egg Harbor City, New Jersey 08215, United States',
      text: 'Hamburg Avenue',
      place_name: 'Hamburg Avenue, Egg Harbor City, New Jersey 08215, United States',
      text_de: 'Hamburg Avenue',
      place_name_de: 'Hamburg Avenue, Egg Harbor City, New Jersey 08215, Vereinigte Staaten',
      text_fr: 'Hamburg Avenue',
      place_name_fr: 'Hamburg Avenue, Egg Harbor City, New Jersey 08215, États-Unis',
      text_nl: 'Hamburg Avenue',
      place_name_nl:
        'Hamburg Avenue, Egg Harbor City, New Jersey 08215, Verenigde Staten van Amerika',
      text_it: 'Hamburg Avenue',
      place_name_it: "Hamburg Avenue, Egg Harbor City, New Jersey 08215, Stati Uniti d'America",
      text_es: 'Hamburg Avenue',
      place_name_es: 'Hamburg Avenue, Egg Harbor City, Nueva Jersey 08215, Estados Unidos',
      text_pt: 'Hamburg Avenue',
      place_name_pt: 'Hamburg Avenue, Egg Harbor City, Nova Jérsia 08215, Estados Unidos',
      text_pl: 'Hamburg Avenue',
      place_name_pl: 'Hamburg Avenue, Egg Harbor City, New Jersey 08215, Stany Zjednoczone',
      text_ru: 'Hamburg Avenue',
      place_name_ru: 'Hamburg Avenue, Эгг Харбор Сити, Нью-Джерси 08215, США',
      center: [-74.634456, 39.551661],
      geometry: {
        type: 'Point',
        coordinates: [-74.634456, 39.551661],
      },
      context: [
        {
          id: 'postcode.22638316',
          mapbox_id: 'dXJuOm1ieHBsYzpBVmx1N0E',
          text_en: '08215',
          text: '08215',
          text_de: '08215',
          text_fr: '08215',
          text_nl: '08215',
          text_it: '08215',
          text_es: '08215',
          text_pt: '08215',
          text_pl: '08215',
          text_ru: '08215',
        },
        {
          id: 'locality.378645228',
          mapbox_id: 'dXJuOm1ieHBsYzpGcEdxN0E',
          text_en: 'Mullica Township',
          language_en: 'en',
          text: 'Mullica Township',
          language: 'en',
          text_de: 'Mullica Township',
          language_de: 'en',
          text_fr: 'Mullica Township',
          language_fr: 'en',
          text_nl: 'Mullica Township',
          language_nl: 'en',
          text_it: 'Mullica Township',
          language_it: 'en',
          text_es: 'Mullica Township',
          language_es: 'en',
          text_pt: 'Mullica Township',
          text_pl: 'Mullica Township',
          language_pl: 'en',
          text_ru: 'Mullica Township',
        },
        {
          id: 'place.97724652',
          mapbox_id: 'dXJuOm1ieHBsYzpCZE1vN0E',
          wikidata: 'Q1082961',
          text_en: 'Egg Harbor City',
          language_en: 'en',
          text: 'Egg Harbor City',
          language: 'en',
          text_de: 'Egg Harbor City',
          language_de: 'de',
          text_fr: 'Egg Harbor City',
          language_fr: 'fr',
          text_nl: 'Egg Harbor City',
          language_nl: 'nl',
          text_it: 'Egg Harbor City',
          language_it: 'it',
          text_es: 'Egg Harbor City',
          language_es: 'es',
          text_pt: 'Egg Harbor City',
          language_pt: 'pt',
          text_pl: 'Egg Harbor City',
          language_pl: 'pl',
          text_ru: 'Эгг Харбор Сити',
          language_ru: 'kk',
        },
        {
          id: 'district.837356',
          mapbox_id: 'dXJuOm1ieHBsYzpETWJz',
          wikidata: 'Q497928',
          text_en: 'Atlantic County',
          language_en: 'en',
          text: 'Atlantic County',
          language: 'en',
          text_de: 'Atlantic County',
          language_de: 'de',
          text_fr: "comté d'Atlantic",
          language_fr: 'fr',
          text_nl: 'Atlantic County',
          language_nl: 'nl',
          text_it: 'contea di Atlantic',
          language_it: 'it',
          text_es: 'Condado de Atlantic',
          language_es: 'es',
          text_pt: 'Condado de Atlantic',
          language_pt: 'pt',
          text_pl: 'Hrabstwo Atlantic',
          language_pl: 'pl',
          text_ru: 'Атлантик',
          language_ru: 'ru',
        },
        {
          id: 'region.156908',
          mapbox_id: 'dXJuOm1ieHBsYzpBbVRz',
          wikidata: 'Q1408',
          short_code: 'US-NJ',
          text_en: 'New Jersey',
          language_en: 'en',
          text: 'New Jersey',
          language: 'en',
          text_de: 'New Jersey',
          language_de: 'de',
          text_fr: 'New Jersey',
          language_fr: 'fr',
          text_nl: 'New Jersey',
          language_nl: 'nl',
          text_it: 'New Jersey',
          language_it: 'it',
          text_es: 'Nueva Jersey',
          language_es: 'es',
          text_pt: 'Nova Jérsia',
          language_pt: 'pt',
          text_pl: 'New Jersey',
          language_pl: 'pl',
          text_ru: 'Нью-Джерси',
          language_ru: 'ru',
        },
        {
          id: 'country.8940',
          mapbox_id: 'dXJuOm1ieHBsYzpJdXc',
          wikidata: 'Q30',
          short_code: 'us',
          text_en: 'United States',
          language_en: 'en',
          text: 'United States',
          language: 'en',
          text_de: 'Vereinigte Staaten',
          language_de: 'de',
          text_fr: 'États-Unis',
          language_fr: 'fr',
          text_nl: 'Verenigde Staten van Amerika',
          language_nl: 'nl',
          text_it: "Stati Uniti d'America",
          language_it: 'it',
          text_es: 'Estados Unidos',
          language_es: 'es',
          text_pt: 'Estados Unidos',
          language_pt: 'pt',
          text_pl: 'Stany Zjednoczone',
          language_pl: 'pl',
          text_ru: 'США',
          language_ru: 'ru',
        },
      ],
    },
  ],
  attribution:
    'NOTICE: © 2025 Mapbox and its suppliers. All rights reserved. Use of this data is subject to the Mapbox Terms of Service (https://www.mapbox.com/about/maps/). This response and the information it contains may not be retained.',
}
