export const paris = {
  type: 'FeatureCollection',
  query: ['paris', 'france'],
  features: [
    {
      id: 'place.894029',
      type: 'Feature',
      place_type: ['region', 'place'],
      relevance: 1,
      properties: {
        mapbox_id: 'dXJuOm1ieHBsYzpEYVJO',
        wikidata: 'Q90',
        short_code: 'FR-75',
      },
      text_en: 'Paris',
      language_en: 'en',
      place_name_en: 'Paris, France',
      text: 'Paris',
      language: 'en',
      place_name: 'Paris, France',
      text_de: 'Paris',
      language_de: 'de',
      place_name_de: 'Paris, Frankreich',
      text_fr: 'Paris',
      language_fr: 'fr',
      place_name_fr: 'Paris, France',
      text_nl: 'Parijs',
      language_nl: 'nl',
      place_name_nl: 'Parijs, Frankrijk',
      text_it: 'Parigi',
      language_it: 'it',
      place_name_it: 'Parigi, Francia',
      text_es: 'París',
      language_es: 'es',
      place_name_es: 'París, Francia',
      text_pt: 'Paris',
      language_pt: 'pt',
      place_name_pt: 'Paris, França',
      text_pl: 'Paryż',
      language_pl: 'pl',
      place_name_pl: 'Paryż, Francja',
      text_ru: 'Париж',
      language_ru: 'ru',
      place_name_ru: 'Париж, Франция',
      bbox: [2.224229, 48.815562, 2.469851, 48.902148],
      center: [2.348392, 48.853495],
      geometry: {
        type: 'Point',
        coordinates: [2.348392, 48.853495],
      },
      context: [
        {
          id: 'country.8781',
          mapbox_id: 'dXJuOm1ieHBsYzpJazA',
          wikidata: 'Q142',
          short_code: 'fr',
          text_en: 'France',
          language_en: 'en',
          text: 'France',
          language: 'en',
          text_de: 'Frankreich',
          language_de: 'de',
          text_fr: 'France',
          language_fr: 'fr',
          text_nl: 'Frankrijk',
          language_nl: 'nl',
          text_it: 'Francia',
          language_it: 'it',
          text_es: 'Francia',
          language_es: 'es',
          text_pt: 'França',
          language_pt: 'pt',
          text_pl: 'Francja',
          language_pl: 'pl',
          text_ru: 'Франция',
          language_ru: 'ru',
        },
      ],
    },
    {
      id: 'address.7942827143743488',
      type: 'Feature',
      place_type: ['address'],
      relevance: 1,
      properties: {
        accuracy: 'street',
        mapbox_id: 'dXJuOm1ieGFkci1zdHI6ZGUyMmI5NjYtODFjMi00YjA4LWJkODgtMGIxNWE2YWE0Y2I2',
      },
      text_en: 'Paris',
      place_name_en: 'Paris, 83170 Brignoles, France',
      text: 'Paris',
      place_name: 'Paris, 83170 Brignoles, France',
      text_de: 'Paris',
      place_name_de: 'Paris, 83170 Brignoles, Frankreich',
      text_fr: 'Paris',
      place_name_fr: 'Paris, 83170 Brignoles, France',
      text_nl: 'Paris',
      place_name_nl: 'Paris, 83170 Brignoles, Frankrijk',
      text_it: 'Paris',
      place_name_it: 'Paris, 83170 Brignoles, Francia',
      text_es: 'Paris',
      place_name_es: 'Paris, 83170 Brignoles, Francia',
      text_pt: 'Paris',
      place_name_pt: 'Paris, 83170 Brignoles, França',
      text_pl: 'Paris',
      place_name_pl: 'Paris, 83170 Brignoles, Francja',
      text_ru: 'Paris',
      place_name_ru: 'Paris, 83170 Бриньоль, Франция',
      center: [6.069561, 43.415211],
      geometry: {
        type: 'Point',
        coordinates: [6.069561, 43.415211],
      },
      context: [
        {
          id: 'neighborhood.23768141',
          mapbox_id: 'dXJuOm1ieHBsYzpBV3FzVFE',
          text_en: 'Extension Annees 80-',
          language_en: 'fr',
          text: 'Extension Annees 80-',
          language: 'fr',
          text_de: 'Extension Annees 80-',
          text_fr: 'Extension Annees 80-',
          language_fr: 'fr',
          text_nl: 'Extension Annees 80-',
          language_nl: 'fr',
          text_it: 'Extension Annees 80-',
          language_it: 'fr',
          text_es: 'Extension Annees 80-',
          language_es: 'fr',
          text_pt: 'Extension Annees 80-',
          text_pl: 'Extension Annees 80-',
          text_ru: 'Extension Annees 80-',
        },
        {
          id: 'postcode.43822669',
          mapbox_id: 'dXJuOm1ieHBsYzpBcHl1VFE',
          text_en: '83170',
          text: '83170',
          text_de: '83170',
          text_fr: '83170',
          text_nl: '83170',
          text_it: '83170',
          text_es: '83170',
          text_pt: '83170',
          text_pl: '83170',
          text_ru: '83170',
        },
        {
          id: 'place.37988429',
          mapbox_id: 'dXJuOm1ieHBsYzpBa09vVFE',
          wikidata: 'Q207584',
          text_en: 'Brignoles',
          language_en: 'en',
          text: 'Brignoles',
          language: 'en',
          text_de: 'Brignoles',
          language_de: 'de',
          text_fr: 'Brignoles',
          language_fr: 'fr',
          text_nl: 'Brignoles',
          language_nl: 'nl',
          text_it: 'Brignoles',
          language_it: 'it',
          text_es: 'Brignoles',
          language_es: 'es',
          text_pt: 'Brignoles',
          language_pt: 'pt',
          text_pl: 'Brignoles',
          language_pl: 'pl',
          text_ru: 'Бриньоль',
          language_ru: 'ru',
        },
        {
          id: 'region.451661',
          mapbox_id: 'dXJuOm1ieHBsYzpCdVJO',
          wikidata: 'Q12789',
          short_code: 'FR-83',
          text_en: 'Var',
          language_en: 'en',
          text: 'Var',
          language: 'en',
          text_de: 'Département Var',
          language_de: 'de',
          text_fr: 'Var',
          language_fr: 'fr',
          text_nl: 'Var',
          language_nl: 'nl',
          text_it: 'Varo',
          language_it: 'it',
          text_es: 'Var',
          language_es: 'es',
          text_pt: 'Var',
          language_pt: 'pt',
          text_pl: 'Var',
          language_pl: 'pl',
          text_ru: 'Вар',
          language_ru: 'ru',
        },
        {
          id: 'country.8781',
          mapbox_id: 'dXJuOm1ieHBsYzpJazA',
          wikidata: 'Q142',
          short_code: 'fr',
          text_en: 'France',
          language_en: 'en',
          text: 'France',
          language: 'en',
          text_de: 'Frankreich',
          language_de: 'de',
          text_fr: 'France',
          language_fr: 'fr',
          text_nl: 'Frankrijk',
          language_nl: 'nl',
          text_it: 'Francia',
          language_it: 'it',
          text_es: 'Francia',
          language_es: 'es',
          text_pt: 'França',
          language_pt: 'pt',
          text_pl: 'Francja',
          language_pl: 'pl',
          text_ru: 'Франция',
          language_ru: 'ru',
        },
      ],
    },
    {
      id: 'address.1606141678135750',
      type: 'Feature',
      place_type: ['address'],
      relevance: 1,
      properties: {
        accuracy: 'street',
        mapbox_id: 'dXJuOm1ieGFkci1zdHI6YTI3YjI5ODYtNGI1ZS00MTBiLThkOTEtOWJjOGUzZmE4NjA0',
      },
      text_en: 'Paris',
      place_name_en: "Paris, 11230 Sainte-Colombe-sur-l'Hers, France",
      text: 'Paris',
      place_name: "Paris, 11230 Sainte-Colombe-sur-l'Hers, France",
      text_de: 'Paris',
      place_name_de: "Paris, 11230 Sainte-Colombe-sur-l'Hers, Frankreich",
      text_fr: 'Paris',
      place_name_fr: "Paris, 11230 Sainte-Colombe-sur-l'Hers, France",
      text_nl: 'Paris',
      place_name_nl: "Paris, 11230 Sainte-Colombe-sur-l'Hers, Frankrijk",
      text_it: 'Paris',
      place_name_it: "Paris, 11230 Sainte-Colombe-sur-l'Hers, Francia",
      text_es: 'Paris',
      place_name_es: "Paris, 11230 Sainte-Colombe-sur-l'Hers, Francia",
      text_pt: 'Paris',
      place_name_pt: "Paris, 11230 Sainte-Colombe-sur-l'Hers, França",
      text_pl: 'Paris',
      place_name_pl: "Paris, 11230 Sainte-Colombe-sur-l'Hers, Francja",
      text_ru: 'Paris',
      place_name_ru: 'Paris, 11230 Сент-Коломб-сюр-л’Эр, Франция',
      center: [1.957948, 42.947813],
      geometry: {
        type: 'Point',
        coordinates: [1.957948, 42.947813],
      },
      context: [
        {
          id: 'postcode.3993165',
          mapbox_id: 'dXJuOm1ieHBsYzpQTzVO',
          text_en: '11230',
          text: '11230',
          text_de: '11230',
          text_fr: '11230',
          text_nl: '11230',
          text_it: '11230',
          text_es: '11230',
          text_pt: '11230',
          text_pl: '11230',
          text_ru: '11230',
        },
        {
          id: 'place.218073165',
          mapbox_id: 'dXJuOm1ieHBsYzpEUCtJVFE',
          wikidata: 'Q1081836',
          text_en: "Sainte-Colombe-sur-l'Hers",
          language_en: 'en',
          text: "Sainte-Colombe-sur-l'Hers",
          language: 'en',
          text_de: "Sainte-Colombe-sur-l'Hers",
          language_de: 'de',
          text_fr: "Sainte-Colombe-sur-l'Hers",
          language_fr: 'fr',
          text_nl: "Sainte-Colombe-sur-l'Hers",
          language_nl: 'nl',
          text_it: "Sainte-Colombe-sur-l'Hers",
          language_it: 'it',
          text_es: "Sainte-Colombe-sur-l'Hers",
          language_es: 'es',
          text_pt: "Sainte-Colombe-sur-l'Hers",
          language_pt: 'pt',
          text_pl: "Sainte-Colombe-sur-l'Hers",
          language_pl: 'pl',
          text_ru: 'Сент-Коломб-сюр-л’Эр',
          language_ru: 'ru',
        },
        {
          id: 'region.713805',
          mapbox_id: 'dXJuOm1ieHBsYzpDdVJO',
          wikidata: 'Q3207',
          short_code: 'FR-11',
          text_en: 'Aude',
          language_en: 'en',
          text: 'Aude',
          language: 'en',
          text_de: 'Département Aude',
          language_de: 'de',
          text_fr: 'Aude',
          language_fr: 'fr',
          text_nl: 'Aude',
          language_nl: 'nl',
          text_it: 'Aude',
          language_it: 'it',
          text_es: 'Aude',
          language_es: 'es',
          text_pt: 'Aude',
          language_pt: 'pt',
          text_pl: 'Aude',
          language_pl: 'pl',
          text_ru: 'Од',
          language_ru: 'ru',
        },
        {
          id: 'country.8781',
          mapbox_id: 'dXJuOm1ieHBsYzpJazA',
          wikidata: 'Q142',
          short_code: 'fr',
          text_en: 'France',
          language_en: 'en',
          text: 'France',
          language: 'en',
          text_de: 'Frankreich',
          language_de: 'de',
          text_fr: 'France',
          language_fr: 'fr',
          text_nl: 'Frankrijk',
          language_nl: 'nl',
          text_it: 'Francia',
          language_it: 'it',
          text_es: 'Francia',
          language_es: 'es',
          text_pt: 'França',
          language_pt: 'pt',
          text_pl: 'Francja',
          language_pl: 'pl',
          text_ru: 'Франция',
          language_ru: 'ru',
        },
      ],
    },
    {
      id: 'address.8644476532166668',
      type: 'Feature',
      place_type: ['address'],
      relevance: 1,
      properties: {
        accuracy: 'street',
        mapbox_id: 'dXJuOm1ieGFkci1zdHI6MTY1YmU5ZTAtMWZiMS00MjhhLThlZmQtN2NkMDVhZjZkNzE3',
      },
      text_en: 'Paris',
      place_name_en: 'Paris, 36120 Jeu-les-Bois, France',
      text: 'Paris',
      place_name: 'Paris, 36120 Jeu-les-Bois, France',
      text_de: 'Paris',
      place_name_de: 'Paris, 36120 Jeu-les-Bois, Frankreich',
      text_fr: 'Paris',
      place_name_fr: 'Paris, 36120 Jeu-les-Bois, France',
      text_nl: 'Paris',
      place_name_nl: 'Paris, 36120 Jeu-les-Bois, Frankrijk',
      text_it: 'Paris',
      place_name_it: 'Paris, 36120 Jeu-les-Bois, Francia',
      text_es: 'Paris',
      place_name_es: 'Paris, 36120 Jeu-les-Bois, Francia',
      text_pt: 'Paris',
      place_name_pt: 'Paris, 36120 Jeu-les-Bois, França',
      text_pl: 'Paris',
      place_name_pl: 'Paris, 36120 Jeu-les-Bois, Francja',
      text_ru: 'Paris',
      place_name_ru: 'Paris, 36120 Же-ле-Буа, Франция',
      center: [1.811749, 46.694191],
      geometry: {
        type: 'Point',
        coordinates: [1.811749, 46.694191],
      },
      context: [
        {
          id: 'postcode.17755725',
          mapbox_id: 'dXJuOm1ieHBsYzpBUTd1VFE',
          text_en: '36120',
          text: '36120',
          text_de: '36120',
          text_fr: '36120',
          text_nl: '36120',
          text_it: '36120',
          text_es: '36120',
          text_pt: '36120',
          text_pl: '36120',
          text_ru: '36120',
        },
        {
          id: 'place.111659085',
          mapbox_id: 'dXJuOm1ieHBsYzpCcWZJVFE',
          wikidata: 'Q596397',
          text_en: 'Jeu-les-Bois',
          language_en: 'en',
          text: 'Jeu-les-Bois',
          language: 'en',
          text_de: 'Jeu-les-Bois',
          language_de: 'de',
          text_fr: 'Jeu-les-Bois',
          language_fr: 'fr',
          text_nl: 'Jeu-les-Bois',
          language_nl: 'nl',
          text_it: 'Jeu-les-Bois',
          language_it: 'it',
          text_es: 'Jeu-les-Bois',
          language_es: 'es',
          text_pt: 'Jeu-les-Bois',
          language_pt: 'pt',
          text_pl: 'Jeu-les-Bois',
          language_pl: 'pl',
          text_ru: 'Же-ле-Буа',
          language_ru: 'ru',
        },
        {
          id: 'region.74829',
          mapbox_id: 'dXJuOm1ieHBsYzpBU1JO',
          wikidata: 'Q12553',
          short_code: 'FR-36',
          text_en: 'Indre',
          language_en: 'en',
          text: 'Indre',
          language: 'en',
          text_de: 'Département Indre',
          language_de: 'de',
          text_fr: 'Indre',
          language_fr: 'fr',
          text_nl: 'Indre',
          language_nl: 'nl',
          text_it: 'Indre',
          language_it: 'it',
          text_es: 'Indre',
          language_es: 'es',
          text_pt: 'Indre',
          language_pt: 'pt',
          text_pl: 'Indre',
          language_pl: 'pl',
          text_ru: 'Эндр',
          language_ru: 'ru',
        },
        {
          id: 'country.8781',
          mapbox_id: 'dXJuOm1ieHBsYzpJazA',
          wikidata: 'Q142',
          short_code: 'fr',
          text_en: 'France',
          language_en: 'en',
          text: 'France',
          language: 'en',
          text_de: 'Frankreich',
          language_de: 'de',
          text_fr: 'France',
          language_fr: 'fr',
          text_nl: 'Frankrijk',
          language_nl: 'nl',
          text_it: 'Francia',
          language_it: 'it',
          text_es: 'Francia',
          language_es: 'es',
          text_pt: 'França',
          language_pt: 'pt',
          text_pl: 'Francja',
          language_pl: 'pl',
          text_ru: 'Франция',
          language_ru: 'ru',
        },
      ],
    },
    {
      id: 'address.8865196537941870',
      type: 'Feature',
      place_type: ['address'],
      relevance: 1,
      properties: {
        accuracy: 'street',
        mapbox_id: 'dXJuOm1ieGFkci1zdHI6NjU2N2E5ODgtN2I4Yi00ZjU2LWEzZWUtYjk4Y2YwMjQzY2Ey',
      },
      text_en: 'Paris',
      place_name_en: 'Paris, 31560 Saint-Léon, France',
      text: 'Paris',
      place_name: 'Paris, 31560 Saint-Léon, France',
      text_de: 'Paris',
      place_name_de: 'Paris, 31560 Saint-Léon, Frankreich',
      text_fr: 'Paris',
      place_name_fr: 'Paris, 31560 Saint-Léon, France',
      text_nl: 'Paris',
      place_name_nl: 'Paris, 31560 Saint-Léon, Frankrijk',
      text_it: 'Paris',
      place_name_it: 'Paris, 31560 Saint-Léon, Francia',
      text_es: 'Paris',
      place_name_es: 'Paris, 31560 Saint-Léon, Francia',
      text_pt: 'Paris',
      place_name_pt: 'Paris, 31560 Saint-Léon, França',
      text_pl: 'Paris',
      place_name_pl: 'Paris, 31560 Saint-Léon, Francja',
      text_ru: 'Paris',
      place_name_ru: 'Paris, 31560 Сен-Леон, Франция',
      center: [1.549305, 43.419569],
      geometry: {
        type: 'Point',
        coordinates: [1.549305, 43.419569],
      },
      context: [
        {
          id: 'postcode.15044173',
          mapbox_id: 'dXJuOm1ieHBsYzo1WTVO',
          text_en: '31560',
          text: '31560',
          text_de: '31560',
          text_fr: '31560',
          text_nl: '31560',
          text_it: '31560',
          text_es: '31560',
          text_pt: '31560',
          text_pl: '31560',
          text_ru: '31560',
        },
        {
          id: 'place.229107789',
          mapbox_id: 'dXJuOm1ieHBsYzpEYWZvVFE',
          wikidata: 'Q1362198',
          text_en: 'Saint-Léon',
          language_en: 'en',
          text: 'Saint-Léon',
          language: 'en',
          text_de: 'Saint-Léon',
          language_de: 'de',
          text_fr: 'Saint-Léon',
          language_fr: 'fr',
          text_nl: 'Saint-Léon',
          language_nl: 'nl',
          text_it: 'Saint-Léon',
          language_it: 'it',
          text_es: 'Saint-Léon',
          language_es: 'es',
          text_pt: 'Saint-Léon',
          language_pt: 'pt',
          text_pl: 'Saint-Léon',
          language_pl: 'pl',
          text_ru: 'Сен-Леон',
          language_ru: 'ru',
        },
        {
          id: 'region.42061',
          mapbox_id: 'dXJuOm1ieHBsYzpwRTA',
          wikidata: 'Q12538',
          short_code: 'FR-31',
          text_en: 'Haute-Garonne',
          language_en: 'en',
          text: 'Haute-Garonne',
          language: 'en',
          text_de: 'Haute-Garonne',
          language_de: 'de',
          text_fr: 'Haute-Garonne',
          language_fr: 'fr',
          text_nl: 'Haute-Garonne',
          language_nl: 'nl',
          text_it: 'Alta Garonna',
          language_it: 'it',
          text_es: 'Alto Garona',
          language_es: 'es',
          text_pt: 'Alta Garona',
          language_pt: 'pt',
          text_pl: 'Górna Garonna',
          language_pl: 'pl',
          text_ru: 'Верхняя Гаронна',
          language_ru: 'ru',
        },
        {
          id: 'country.8781',
          mapbox_id: 'dXJuOm1ieHBsYzpJazA',
          wikidata: 'Q142',
          short_code: 'fr',
          text_en: 'France',
          language_en: 'en',
          text: 'France',
          language: 'en',
          text_de: 'Frankreich',
          language_de: 'de',
          text_fr: 'France',
          language_fr: 'fr',
          text_nl: 'Frankrijk',
          language_nl: 'nl',
          text_it: 'Francia',
          language_it: 'it',
          text_es: 'Francia',
          language_es: 'es',
          text_pt: 'França',
          language_pt: 'pt',
          text_pl: 'Francja',
          language_pl: 'pl',
          text_ru: 'Франция',
          language_ru: 'ru',
        },
      ],
    },
  ],
  attribution:
    'NOTICE: © 2025 Mapbox and its suppliers. All rights reserved. Use of this data is subject to the Mapbox Terms of Service (https://www.mapbox.com/about/maps/). This response and the information it contains may not be retained.',
}
