query policy {
  policy {
    publicRegistration
    inviteRegistration
    askForRealName
    requireLocation
    categoriesActive
    badgesEnabled
    apiKeysEnabled
    apiKeysMaxPerUser
    maxGroupPinnedPosts
  }
}
