query policyDefaults {
  policyDefaults {
    defaults {
      publicRegistration
      inviteRegistration
      askForRealName
      requireLocation
      inviteLinkLimit
      inviteCodesPersonalPerUser
      inviteCodesGroupPerUser
      categoriesActive
      badgesEnabled
      apiKeysEnabled
      apiKeysMaxPerUser
      maxPinnedPosts
      maxGroupPinnedPosts
    }
    lastChange {
      actor
      timestamp
    }
  }
}
