query policyDefaults {
  policyDefaults {
    defaults {
      publicRegistration
      inviteRegistration
      categoriesActive
      apiKeysEnabled
    }
    lastChange {
      actor
      timestamp
    }
  }
}
