kind: Deployment
apiVersion: apps/v1
metadata:
  name:  {{ .Release.Name }}-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-webapp
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-webapp
    spec:
      restartPolicy: Always
      containers:
      - name: {{ .Release.Name }}-webapp
        image: "{{ .Values.webapp.image.repository }}:{{ .Values.webapp.image.tag | default (include "defaultTag" .)  }}"
        imagePullPolicy: {{ quote .Values.global.image.pullPolicy }}
        {{- include "resources" .Values.webapp.resources | indent 8 }}
        ports:
        - containerPort: 3000
        env:
        - name: WEBSOCKETS_URI
          value: "wss://{{ .Values.domain }}/api/graphql"
        - name: HOST
          value: "0.0.0.0"
        - name: GRAPHQL_URI
          value: "http://{{ .Release.Name }}-backend:4000"
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-webapp-env
        - secretRef:
            name: {{ .Release.Name }}-webapp-secret-env
