type ApiKey {
  id: ID!
  name: String!
  keyPrefix: String!
  createdAt: String!
  lastUsedAt: String
  expiresAt: String
  disabled: Boolean!
  disabledAt: String
  owner: User @relation(name: "HAS_API_KEY", direction: "IN")
}

type ApiKeyWithSecret {
  apiKey: ApiKey!
  secret: String!
}

type ApiKeyUserSummary {
  user: User!
  activeCount: Int!
  revokedCount: Int!
  postsCount: Int!
  commentsCount: Int!
  lastActivity: String
}

enum ApiKeyUserOrder {
  LAST_ACTIVITY
  ACTIVE_KEYS
  POSTS_COUNT
  COMMENTS_COUNT
}

type Query {
  myApiKeys: [ApiKey!]!
  apiKeyUsers(orderBy: ApiKeyUserOrder, first: Int, offset: Int): [ApiKeyUserSummary!]!
  apiKeysForUser(userId: ID!): [ApiKey!]!
}

type Mutation {
  createApiKey(name: String!, expiresInDays: Int): ApiKeyWithSecret!
  updateApiKey(id: ID!, name: String!): ApiKey!
  revokeApiKey(id: ID!): Boolean!
  adminRevokeApiKey(id: ID!): Boolean!
  adminRevokeUserApiKeys(userId: ID!): Int!
}
