type InviteCode {
  code: ID!
  createdAt: String!
  generatedBy: User @relation(name: "GENERATED", direction: "IN")
  redeemedBy: [User] @relation(name: "REDEEMED", direction: "IN")
  expiresAt: String
  comment: String

  invitedTo: Group @neo4j_ignore
  invitedFrom: User! @neo4j_ignore

  isValid: Boolean! @neo4j_ignore
}

type Query {
  validateInviteCode(code: String!): InviteCode
}

type Mutation {
  generatePersonalInviteCode(expiresAt: String = null): InviteCode!
  generateGroupInviteCode(groupId: ID!, expiresAt: String = null): InviteCode!
  invalidateInviteCode(code: String!): InviteCode
  redeemInviteCode(code: String!): Boolean!
}
