type Query {
  policy: Policy!
  policyDefaults: Policy!
  policyLastChange: PolicyLastChange
}

type PolicyLastChange {
  actor: String!
  timestamp: String!
}

type Policy {
  publicRegistration: Boolean!
  inviteRegistration: Boolean!
  categoriesActive: Boolean!
  apiKeysEnabled: Boolean
}

type PolicyChangeEvent {
  key: String!
  value: String!
  actor: String!
  timestamp: String!
}

type Mutation {
  setPolicy(key: String!, value: String!): PolicyChangeEvent!
  resetPolicy(key: String!): PolicyChangeEvent!
}

type Subscription {
  policyChanged: PolicyChangeEvent!
}
