{{- if .Values.imagePullCredentials.registries }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "imagePullSecretName" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "imagePullSecretDockerConfigJson" . | b64enc }}
{{- end }}
