kind: Deployment
apiVersion: apps/v1
metadata:
  name:  {{ .Release.Name }}-webapp
  labels:
    app.kubernetes.io/name:       "{{ .Chart.Name }}"
    app.kubernetes.io/instance:   "{{ .Release.Name }}"
    app.kubernetes.io/version:    "{{ .Chart.AppVersion }}"
    app.kubernetes.io/component:  "deployment-webapp"
    app.kubernetes.io/part-of:    "{{ .Chart.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart:                "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.WEBAPP.REPLICAS }}
  minReadySeconds: {{ .Values.WEBAPP.MIN_READY_SECONDS }}
  progressDeadlineSeconds: {{ .Values.WEBAPP.PROGRESS_DEADLINE_SECONDS }}
  revisionHistoryLimit: {{ .Values.WEBAPP.REVISIONS_HISTORY_LIMIT }}
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-webapp
  template:
    metadata:
      annotations:
        # make sure the pod is redeployed
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: {{ .Release.Name }}-webapp
    spec:
      containers:
      - name: container-{{ .Release.Name }}-webapp
        image: "{{ .Values.WEBAPP.DOCKER_IMAGE_REPO }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.WEBAPP.DOCKER_IMAGE_PULL_POLICY }}
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: configmap-{{ .Release.Name }}-webapp
        - secretRef:
            name: secret-{{ .Release.Name }}-webapp
        resources:
          requests:
            memory: {{ .Values.WEBAPP.RESOURCE_REQUESTS_MEMORY | default "500M" | quote }}
          limits:
            memory: {{ .Values.WEBAPP.RESOURCE_LIMITS_MEMORY | default "1G" | quote }}
      restartPolicy: {{ .Values.WEBAPP.CONTAINER_RESTART_POLICY }}
      terminationGracePeriodSeconds: {{ .Values.WEBAPP.CONTAINER_TERMINATION_GRACE_PERIOD_SECONDS }}