mutation setVerificationBadge($badgeId: ID!, $userId: ID!) {
  setVerificationBadge(badgeId: $badgeId, userId: $userId) {
    id
    badgeVerification {
      id
      isDefault
    }
    badgeTrophies {
      id
    }
  }
}
