kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app.kubernetes.io/name:	"{{ .Chart.Name }}"
    app.kubernetes.io/instance:	"{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/component: "service-backend"
    app.kubernetes.io/part-of:	"{{ .Chart.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  ports:
    - name: {{ .Release.Name }}-graphql
      port: 4000
      targetPort: 4000
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-backend
