# please duplicate template file and rename to "dns.values.yaml" and fill in your value

provider: digitalocean
digitalocean:
  # create the API token at https://cloud.digitalocean.com/account/api/tokens
  # needs read + write
  apiToken: "TODO"
domainFilters:
  # domains you want external-dns to be able to edit
  - TODO.TODO
rbac:
  create: true