# please duplicate template file and rename to "nginx.values.yaml" and fill in your value

controller:
  kind: DaemonSet
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  ingressClass: nginx
  daemonset:
    useHostPort: true
  service:
    type: ClusterIP
rbac:
  create: true