mutation CreateMessage($roomId: ID, $userId: ID, $content: String, $files: [FileInput]) {
  CreateMessage(roomId: $roomId, userId: $userId, content: $content, files: $files) {
    id
    content
    senderId
    username
    avatar
    date
    room {
      id
    }
    saved
    distributed
    seen
    files {
      url
      name
      type
    }
  }
}
