query Room($first: Int, $before: String, $id: ID, $userId: ID, $groupId: ID) {
  Room(first: $first, before: $before, id: $id, userId: $userId, groupId: $groupId) {
    id
    roomId
    roomName
    avatar
    lastMessageAt
    unreadCount
    lastMessage {
      _id
      id
      content
      senderId
      username
      avatar
      date
      saved
      distributed
      seen
    }
    users {
      _id
      id
      name
      avatar {
        url
      }
    }
  }
}
