query authenticatedValidateInviteCode($code: String!) {
  validateInviteCode(code: $code) {
    code
    invitedTo {
      id
      visibility
      name
      about
      avatar {
        url
      }
    }
    generatedBy {
      id
      name
      avatar {
        url
      }
    }
    isValid
  }
}
