mutation DeleteUser($id: ID!, $resource: [Deletable]) {
  DeleteUser(id: $id, resource: $resource) {
    id
    name
    about
    deleted
    contributions {
      id
      content
      deleted
      comments {
        id
        content
        deleted
      }
    }
    comments {
      id
      content
      deleted
    }
  }
}
