query mentionSuggestions($query: String, $postId: ID, $groupId: ID, $first: Int) {
  mentionSuggestions(query: $query, postId: $postId, groupId: $groupId, first: $first) {
    relation
    user {
      id
      slug
      name
    }
  }
}
