name: "frontend:deploy:docs to github"
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08 # v4.1.7

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@875651a25c97353b9dcfc78c0c59b7dc09b8dbda # v1.8.1
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #TARGET_REPO: username/repo
        #TARGET_BRANCH: master
        BUILD_SCRIPT: npm install && npm run docs:build
        BUILD_DIR: build/docs/
        VUEPRESS_BASE: "boilerplate-frontend"