mutation unpinPost($id: ID!) {
  unpinPost(id: $id) {
    id
    title
    content
    author {
      id
      name
      slug
    }
    pinnedBy {
      id
      name
      roleName
    }
    createdAt
    updatedAt
    pinned
    pinnedAt
  }
}
