mutation UpdatePost(
  $id: ID!
  $title: String!
  $slug: String
  $content: String!
  $image: ImageInput
  $categoryIds: [ID]
  $postType: PostType
  $eventInput: _EventInput
) {
  UpdatePost(
    id: $id
    title: $title
    slug: $slug
    content: $content
    image: $image
    categoryIds: $categoryIds
    postType: $postType
    eventInput: $eventInput
  ) {
    id
    title
    slug
    content
    author {
      id
      name
      slug
    }
    createdAt
    updatedAt
    categories {
      id
    }
    postType
    eventStart
    eventLocationName
    eventVenue
    eventLocation {
      id
      lng
      lat
    }
  }
}
