// Brand the standalone maintenance page from a brand's typed config.
//
//   node scripts/build-maintenance-branding.ts <brand-dir> <maintenance-dir>
//
// The maintenance page is a SEPARATE static Nuxt app served (by nginx) when the main app is down —
// so it cannot use the runtime branding injection (the webapp that serves /branding/* is offline).
// It is therefore branded at BUILD time: this overlays the brand's theme + logo onto the maintenance
// app before it is built, the same way the webapp overlay works.
//
// It reuses the brand's runtime theme (branding.theme.cssVars → the maintenance already styles with
// var(--color-primary) etc.) and its squared logo, so a brand defines colours + logo ONCE and both
// the live app and the maintenance page follow. Idempotent (re-runnable): the brand block in
// branding.css is delimited and regenerated.
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { basename, join, resolve } from 'node:path'

import { composeArchive } from '../dist/discover.js'
import { readTarGz } from '../dist/tar.js'
import { resolveThemeColor } from '../dist/theme.js'

import { buildBrandArchive } from './lib/build-brandings.ts'

const [brandArg, maintenanceArg] = process.argv.slice(2)
if (!brandArg || !maintenanceArg) {
  console.error('usage: build-maintenance-branding.ts <brand-dir> <maintenance-dir>')
  process.exit(1)
}
const brandDir = resolve(brandArg)
const maintenanceDir = resolve(maintenanceArg)

// Bundle the brand into its archive and read config + logo back FROM it — the same artifact the live
// app + serverMiddleware consume, so the maintenance page can't drift from them.
const { id, gz } = await buildBrandArchive(brandDir)
const archive = readTarGz(gz)
// Compose the effective config from the archive's instance fragments (no merged branding.json).
// buildBrandArchive always writes a manifest, so composeArchive is non-null here.
const config = composeArchive(archive)
if (!config) throw new Error(`could not compose config from archive for ${id}`)
const cssVars = config.theme.cssVars

// --- 1. Colours: append the brand's :root overrides to the maintenance branding.css --------------
const cssPath = join(maintenanceDir, 'app/assets/css/branding.css')
if (!existsSync(cssPath)) throw new Error(`maintenance branding.css not found: ${cssPath}`)
const MARK = '/* === brand overrides (generated by build-maintenance-branding.ts) === */'
let css = readFileSync(cssPath, 'utf8')
const at = css.indexOf(MARK)
const hadBlock = at !== -1
if (hadBlock) css = css.slice(0, at).trimEnd() + '\n' // strip a previous generated block

// Colours only (the maintenance page styles with var(--color-*)); fonts stay the maintenance
// default (its body uses LatoWeb literally) — a brand font would need the file copied + the body
// switched to var(--font-family-text), a separate follow-up.
const varCount = Object.keys(cssVars).length
if (varCount) {
  const vars = Object.entries(cssVars)
    .map(([k, v]) => `  --${k}: ${v};`)
    .join('\n')
  css += `\n${MARK}\n:root {\n${vars}\n}\n`
}
// Write when there are vars to apply OR a previous block was stripped — the latter keeps the script
// idempotent: a rebuild for a brand that has since dropped its cssVars removes the stale block.
if (varCount || hadBlock) {
  writeFileSync(cssPath, css)

  console.log(
    varCount
      ? `[maintenance] colours → ${cssPath} (${varCount} vars)`
      : `[maintenance] removed stale brand block → ${cssPath}`,
  )
}

// --- 2. Logo: read the brand's squared logo FROM the archive → maintenance public path -----------
const logoPath = config.logos.signupPath // the squared logo, namespaced /branding/<id>/…
const prefix = `/branding/${id}/`
if (logoPath.startsWith(prefix)) {
  const entry = logoPath.slice(prefix.length) // e.g. assets/logo-squared.svg
  const data = archive.get(entry)
  if (data) {
    const dest = join(maintenanceDir, 'public/img/custom', basename(entry))
    writeFileSync(dest, data)
    // The maintenance app references /img/custom/logo-squared.svg — keep that stable name too.
    const stable = join(maintenanceDir, 'public/img/custom/logo-squared.svg')
    if (dest !== stable && entry.endsWith('.svg')) writeFileSync(stable, data)

    console.log(`[maintenance] logo → ${dest}`)
  } else {
    console.warn(`[maintenance] ! logo entry not in archive: ${entry}`)
  }
}

// --- 3. Metadata: theme-color + app identity for the <head> --------------------------------------
// `config` is fully merged, so every metadata field is present (the ocelot vanilla defaults when the
// brand didn't override them) — no per-field fallbacks needed.
const m = config.metadata
// Browser-chrome colour = the brand's primary colour (no separate metadata.themeColor field).
const themeColor = resolveThemeColor(cssVars)
const metaPath = join(maintenanceDir, 'app/constants/metadata.ts')
if (existsSync(metaPath)) {
  const meta = {
    APPLICATION_NAME: m.applicationName,
    APPLICATION_SHORT_NAME: m.applicationShortName,
    APPLICATION_DESCRIPTION: m.applicationDescription,
    ORGANIZATION_NAME: m.organizationName,
    ORGANIZATION_JURISDICTION: m.organizationJurisdiction,
    THEME_COLOR: themeColor,
    OG_IMAGE: m.ogImage,
    OG_IMAGE_ALT: m.ogImageAlt,
    OG_IMAGE_WIDTH: m.ogImageWidth,
    OG_IMAGE_HEIGHT: m.ogImageHeight,
    OG_IMAGE_TYPE: m.ogImageType,
  }
  const body = Object.entries(meta)
    .map(([k, v]) => `  ${k}: ${JSON.stringify(v)},`)
    .join('\n')
  writeFileSync(
    metaPath,
    `// Generated by build-maintenance-branding.ts from the brand config.\nexport default {\n${body}\n};\n`,
  )

  console.log(`[maintenance] metadata → ${metaPath} (theme-color ${themeColor})`)
}
