// Writes the committed framework-token snapshot (src/frameworkTokens.snapshot.json) from the webapp's
// stylesheets. The snapshot itself and the reason it exists live next to the data, in src/frameworkTokens.ts;
// only the GENERATOR is here, so that reading the tokens at runtime never pulls postcss into a server
// process (see lib/css.ts).
//
// Run it with `npm run tokens:snapshot`. framework-tokens.spec.ts fails when the snapshot drifts from
// the stylesheets, in the checkouts where those can be read.
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

import { computeCatalog } from './theme-catalog.ts'

const SNAPSHOT = new URL('../src/frameworkTokens.generated.ts', import.meta.url)

const HEADER = `// GENERATED by \`npm run tokens:snapshot\` — do not edit.
//
// A TypeScript module rather than the JSON it looks like, because src/ is type-checked as ESM
// (module: nodenext, which demands an \`with { type: 'json' }\` import attribute) and COMPILED as
// CommonJS (module: commonjs, where that attribute is an error). No single JSON import satisfies both;
// a plain data module satisfies neither constraint by having none.
//
// Why the values live here at all: see src/frameworkTokens.ts.
`

/** Prettier's own quoting rules, so the generated file needs no reformatting to pass lint. */
function quote(value: string): string {
  return value.includes("'") && !value.includes('"')
    ? JSON.stringify(value)
    : `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
}

/** The module source for a token map — exported so the drift guard can compare without writing. */
export function renderFrameworkTokens(tokens: Record<string, string>): string {
  // Sorted, so a regenerated file diffs by VALUE and not by whatever order readdir returned.
  const entries = Object.entries(tokens)
    .sort(([a], [b]) => (a < b ? -1 : 1))
    .map(([name, value]) => {
      // Prettier breaks after the colon when the entry would exceed printWidth (100) — matching it
      // here is what keeps the generated file lint-clean without an eslint-disable header.
      const line = `  ${quote(name)}: ${quote(value)},`
      return line.length <= 100 ? line : `  ${quote(name)}:\n    ${quote(value)},`
    })
  return `${HEADER}
export const FRAMEWORK_TOKENS: Record<string, string> = {
${entries.join('\n')}
}
`
}

/** Rewrite the generated module from the webapp's stylesheets. Only meaningful in this repository. */
export function writeFrameworkTokens(outPath?: string): string {
  const out = outPath ?? fileURLToPath(SNAPSHOT)
  writeFileSync(out, renderFrameworkTokens(computeCatalog()))
  return out
}
