name: CI Cache Verification
on:
  push:
    paths:
      - '.github/workflows/cache-verify.yml'
  workflow_dispatch:
jobs:
  build-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: backend
            context: ./backend
            dockerfile: ./backend/Dockerfile
            target: build
          - name: webapp
            context: ./webapp
            dockerfile: ./webapp/Dockerfile
            target: build
          - name: neo4j
            context: ./neo4j
            dockerfile: ./neo4j/Dockerfile
            target: community
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build ${{ matrix.name }} image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          target: ${{ matrix.target }}
          push: false
          outputs: type=docker,dest=/tmp/${{ matrix.name }}.tar
      - name: Upload ${{ matrix.name }} image
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}-image
          path: /tmp/${{ matrix.name }}.tar
  cache-environment:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Compute cache key
        id: cache-key
        run: |
          BACKEND_HASH=$(sha256sum backend/yarn.lock | cut -d' ' -f1)
          WEBAPP_HASH=$(sha256sum webapp/yarn.lock | cut -d' ' -f1)
          CYPRESS_HASH=$(sha256sum cypress/yarn.lock | cut -d' ' -f1 2>/dev/null || echo "none")
          echo "key=ci-all-cache-${{ runner.os }}-${BACKEND_HASH}-${WEBAPP_HASH}-${CYPRESS_HASH}" >> $GITHUB_OUTPUT

      - name: Show lockfile hashes (debug)
        run: |
          echo "backend/yarn.lock hash: $(sha256sum backend/yarn.lock | cut -d' ' -f1)"
          echo "webapp/yarn.lock hash: $(sha256sum webapp/yarn.lock | cut -d' ' -f1)"
          echo "cypress/yarn.lock hash: $(sha256sum cypress/yarn.lock | cut -d' ' -f1 2>/dev/null || echo 'not found')"

      - name: Restore full CI cache
        id: restore-cache
        uses: actions/cache@v4
        with:
          path: |
            backend/node_modules
            webapp/node_modules
            ~/.cache/Cypress
            /opt/cucumber-json-formatter
          key: ${{ steps.cache-key.outputs.key }}
          restore-keys: |
            ci-all-cache-${{ runner.os }}-
            ci-all-cache-

      - name: Cache status > Hit
        if: steps.restore-cache.outputs.cache-hit == 'true'
        run: echo "✅ Cache was hit!"

      - name: Cache status > Miss
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: echo "❌ Cache was missed."

      - name: Ensure Cypress and Formatter are present
        run: |
          # Install Cypress CLI if needed
          if ! npx --no-install cypress --version >/dev/null 2>&1; then
            yarn global add cypress
          fi
          npx cypress verify
          # Install cucumber-json-formatter if missing
          if [ ! -f /opt/cucumber-json-formatter ]; then
            wget --no-verbose -O /opt/cucumber-json-formatter "https://github.com/cucumber/json-formatter/releases/download/v19.0.0/cucumber-json-formatter-linux-386"
            chmod +x /opt/cucumber-json-formatter
          fi

      - name: Print Cypress version
        run: npx cypress --version

      - name: Print Formatter version/help
        run: /opt/cucumber-json-formatter --help || echo "Formatter missing"
  consolidate-environment:
    runs-on: ubuntu-latest
    needs: [build-images, cache-environment]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore full CI cache
        id: restore-cache
        uses: actions/cache@v4
        with:
          path: |
            backend/node_modules
            webapp/node_modules
            ~/.cache/Cypress
            /opt/cucumber-json-formatter
          key: ${{ needs.cache-environment.outputs.cache-key }}
          restore-keys: |
            ci-all-cache-${{ runner.os }}-
            ci-all-cache-

      # check for node modules etc
      - name: Check node_modules exist
        run: |
          [ -d backend/node_modules ] && echo "✅ backend/node_modules ok" || (echo "❌ backend/node_modules missing" && exit 1)
          [ -d webapp/node_modules ] && echo "✅ webapp/node_modules ok" || (echo "❌ webapp/node_modules missing" && exit 1)
      - name: Check Cypress binary cache
        run: |
          [ -d ~/.cache/Cypress ] && echo "✅ Cypress cache ok" || (echo "❌ Cypress cache missing" && exit 1)

      - name: Check Cypress CLI & version
        run: |
          npx --no-install cypress --version && npx cypress verify

      - name: Check cucumber-json-formatter
        run: |
          [ -x /opt/cucumber-json-formatter ] && /opt/cucumber-json-formatter --help || (echo "❌ Formatter missing" && exit 1)

      - name: Download Docker image artifacts
        uses: actions/download-artifact@v4
        with:
          path: /tmp

      - name: Load Docker images
        run: |
          docker load < /tmp/backend-image/backend.tar
          docker load < /tmp/webapp-image/webapp.tar
          docker load < /tmp/neo4j-image/neo4j.tar

      - name: Setup .env files
        run: |
          cp webapp/.env.template webapp/.env || touch webapp/.env
          cp backend/.env.test_e2e backend/.env || touch backend/.env

      - name: Start system
        run: |
          docker compose -f docker-compose.yml -f docker-compose.test.yml up --detach

      - name: Wait for webapp
        run: |
          echo "Waiting for http://localhost:3000..."
          for i in {1..15}; do
            curl -sf http://localhost:3000 && echo "✅ Ready" && exit 0
            echo "$i..." && sleep 2
          done
          echo "❌ Webapp did not respond in time" && exit 1