###############################################################################
# A Github repo has max 10 GB of cache.
# https://github.blog/changelog/2021-11-23-github-actions-cache-size-is-now-increased-to-10gb-per-repository/
#
# To avoid "cache thrashing" by their cache eviction policy it is recommended
# to apply a cache cleanup workflow at PR closing to dele cache leftovers of
# the current branch:
# https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries
###############################################################################

name: ocelot.social cache cleanup on pr closing

on:
  pull_request:
    types:
      - closed

jobs:
  clean-branch-cache:
    name: Cleanup branch cache
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      actions: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f # v4.2.2

      - name: Cleanup
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          echo "Cache cleanup for PR $PR_NUMBER"
          
          echo "Search for caches with prefix '$PR_NUMBER-'..."
          cacheKeys=$(gh cache list --json key --jq '.[] | select(.key | startswith("'"$PR_NUMBER-"'")) | .key')
          
          if [ -z "$cacheKeys" ]; then
            echo "No caches found with prefix '$PR_NUMBER-'. Nothing to do."
          else            
            echo "Delete caches..."
            for cacheKey in $cacheKeys
            do
              echo "Deleting cache: $cacheKey"
              gh cache delete "$cacheKey" --confirm
              if [ $? -eq 0 ]; then
                echo "Successfully deleted cache: $cacheKey"
              else
                echo "Failed to delete cache: $cacheKey"
              fi
            done
            
            echo "Cache cleanup completed"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}