name: ocelot.social copy .md files to docs.ocelot.social CI

on:
  push:
    branches:
      - trigger-docs.ocelot.social-deployment-by-markdown-file-changes-in-master-branch

jobs:
  files-changed:
    name: Detect File Changes - Markdown files
    runs-on: ubuntu-latest
    outputs:
      markdown-files: ${{ steps.changes.outputs.markdown-files }}
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Check for markdown file changes
        uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/file-filters.yml
          list-files: shell

  copy-md-files:
    name: Copy markdown files to docs.ocelot.social
    if: needs.files-changed.outputs.markdown-files == 'true'
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Select .md files in origin structure
      run: |
        mkdir docs
        rsync -av --include="*.md" --include="*/" --exclude="*" ./ ./docs/

    - name: Copy .md files
      uses: RomanosTrechlis/actions-copy-files@master
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        source-files: ./docs/*
        destination-username: 'Ocelot-Social-Community'
        destination-repository: 'Ocelot-Social'
        destination-directory: 'docs/'
        commit-email: 'lenzmath@posteo.de'
        commit-username: 'mahula' 
