name: ocelot.social webapp test CI


on: [push]

jobs:
  files-changed:
    name: Detect File Changes - Webapp
    runs-on: ubuntu-latest
    outputs:
      docker: ${{ steps.changes.outputs.docker }}
      webapp: ${{ steps.changes.outputs.webapp }}
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Check for frontend file changes
        uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/file-filters.yml
          list-files: shell

  prepare:
    name: Prepare
    if: needs.files-changed.outputs.webapp == 'true
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check translation files
        run: |
          scripts/translations/sort.sh
          scripts/translations/missing-keys.sh
          
  build_test_webapp:
    name: Docker Build Test - Webapp
    if: needs.files-changed.outputs.docker == 'true' || needs.files-changed.outputs.webapp == 'true
    needs: [files-changed, prepare]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: webapp | Build 'test' image
        run: |
          docker build --target test -t "ocelotsocialnetwork/webapp:test" webapp/
          docker save "ocelotsocialnetwork/webapp:test" > /tmp/webapp.tar

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-webapp-test
          path: /tmp/webapp.tar

  lint_webapp:
    name: Lint Webapp
    if: needs.files-changed.outputs.webapp == 'true
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: webapp | Lint
        run: cd webapp && yarn && yarn run lint

  unit_test_webapp:
    name: Unit Tests - Webapp
    if: needs.files-changed.outputs.docker == 'true' || needs.files-changed.outputs.webapp == 'true
    needs: [files-changed, build_test_webapp]
    runs-on: ubuntu-latest
    permissions: 
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Docker Image (Webapp)
        uses: actions/download-artifact@v3
        with:
          name: docker-webapp-test
          path: /tmp

      - name: Load Docker Image
        run: docker load < /tmp/webapp.tar

      - name: backend | copy env files webapp
        run: cp webapp/.env.template webapp/.env

      - name: backend | copy env files backend
        run: cp backend/.env.template backend/.env

      - name: backend | docker-compose
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml up --detach --no-deps webapp

      - name: webapp | Unit tests incl. coverage check
        run: docker-compose exec -T webapp yarn test

